// Different types of context. 
export const CONTEXT_TYPE_INTERNAL_STATE = "CONTEXT_TYPE_INTERNAL_STATE";
export const CONTEXT_TYPE_TIME = "CONTEXT_TYPE_TIME";
export const CONTEXT_TYPE_QUANTITY = "CONTEXT_TYPE_QUANTITY";
export const CONTEXT_TYPE_TOPIC_RELATIVE_POSITION = "CONTEXT_TYPE_TOPIC_RELATIVE_POSITION";
export const CONTEXT_TYPE_DIRECTION = "CONTEXT_TYPE_DIRECTION";
export const CONTEXT_TYPE_AGENCY = "CONTEXT_TYPE_AGENCY";
export const CONTEXT_TYPE_PURPOSE = "CONTEXT_TYPE_PURPOSE";

/* STATE */


/* Context Internal State */

export const CONTEXT_INTERNAL_STATE_ON = "CONTEXT_INTERNAL_STATE_ON";
export const CONTEXT_INTERNAL_STATE_OFF = "CONTEXT_INTERNAL_STATE_OFF";
export const CONTEXT_INTERNAL_STATE_DEAD = "CONTEXT_INTERNAL_STATE_DEAD";
export const CONTEXT_INTERNAL_STATE_ALIVE = "CONTEXT_INTERNAL_STATE_ALIVE";

/* Context Time */

export const CONTEXT_TIME_PAST = "CONTEXT_TIME_PAST";
export const CONTEXT_TIME_PRESENT = "CONTEXT_TIME_PRESENT";
export const CONTEXT_TIME_FUTURE = "CONTEXT_TIME_FUTURE";

// /* TIME */

// // // Date
// export const CONTEXT_TIME_DATE_ON = "CONTEXT_TIME_DATE_ON";
// export const CONTEXT_TIME_DATE_IN = "CONTEXT_TIME_DATE_IN";
// export const CONTEXT_TIME_DATE_AT = "CONTEXT_TIME_DATE_AT";

// // // Point of time
// export const CONTEXT_TIME_POINT_OF_TIME_SINCE = "CONTEXT_TIME_POINT_OF_TIME_SINCE";
// export const CONTEXT_TIME_POINT_OF_TIME_BEFORE = "CONTEXT_TIME_POINT_OF_TIME_BEFORE";
// export const CONTEXT_TIME_POINT_OF_TIME_AFTER = "CONTEXT_TIME_POINT_OF_TIME_AFTER";
// export const CONTEXT_TIME_TIME_BY = "CONTEXT_TIME_TIME_BY";
// export const CONTEXT_TIME_TIME_AGO = "CONTEXT_TIME_TIME_AGO";

// // // Period of time
// export const CONTEXT_TIME_PERIOD_OF_TIME_FOR = "CONTEXT_TIME_PERIOD_OF_TIME_FOR";
// export const CONTEXT_TIME_PERIOD_OF_TIME_TO = "CONTEXT_TIME_PERIOD_OF_TIME_TO";
// export const CONTEXT_TIME_PERIOD_OF_TIME_TILL = "CONTEXT_TIME_PERIOD_OF_TIME_TILL";
// export const CONTEXT_TIME_PERIOD_OF_TIME_UNTIL = "CONTEXT_TIME_PERIOD_OF_TIME_UNTIL";

// // // Telling the time
// export const CONTEXT_TIME_TELL_TIME_TO = "CONTEXT_TIME_TELL_TIME_TO";
// export const CONTEXT_TIME_TELL_TIME_PAST = "CONTEXT_TIME_TELL_TIME_PAST";



/* Context Quantity */

export const CONTEXT_QUANTITY_SINGLE = "CONTEXT_QUANTITY_SINGLE";
export const CONTEXT_QUANTITY_MULTIPLE = "CONTEXT_QUANTITY_MULTIPLE";


/* Context Topic Relative Position */
// if topic is object. 

export const CONTEXT_TOPIC_RELATIVE_POSITION_NEAR = "CONTEXT_TOPIC_RELATIVE_POSITION_NEAR";
export const CONTEXT_TOPIC_RELATIVE_POSITION_FAR = "CONTEXT_TOPIC_RELATIVE_POSITION_FAR";

export const CONTEXT_TOPIC_RELATIVE_POSITION_ABOVE = "CONTEXT_TOPIC_RELATIVE_POSITION_ABOVE";
// export const PREP_POSITION_OVER = "PREP_POSITION_OVER";
// export const PREP_POSITION_UP = "PREP_POSITION_UP";

export const CONTEXT_TOPIC_RELATIVE_POSITION_BELOW = "CONTEXT_TOPIC_RELATIVE_POSITION_BELOW";
// export const PREP_POSITION_UNDER = "PREP_POSITION_UNDER";
// export const PREP_POSITION_UNDERNEATH	= "PREP_POSITION_UNDERNEATH";
// export const PREP_POSITION_BENEATH = "PREP_POSITION_BENEATH";
// export const PREP_POSITION_DOWN = "PREP_POSITION_DOWN";

export const CONTEXT_TOPIC_RELATIVE_POSITION_BEHIND = "CONTEXT_TOPIC_RELATIVE_POSITION_BEHIND";
export const CONTEXT_TOPIC_RELATIVE_POSITION_IN_FRONT = "CONTEXT_TOPIC_RELATIVE_POSITION_IN_FRONT";

export const CONTEXT_TOPIC_RELATIVE_POSITION_BESIDE = "CONTEXT_TOPIC_RELATIVE_POSITION_BESIDE";
// export const CONTEXT_TOPIC_RELATIVE_POSITION_AT = "CONTEXT_TOPIC_RELATIVE_POSITION_AT"; 
// export const CONTEXT_TOPIC_RELATIVE_POSITION_NEXT = "CONTEXT_TOPIC_RELATIVE_POSITION_NEXT";
// export const CONTEXT_TOPIC_RELATIVE_POSITION_TO = "CONTEXT_TOPIC_RELATIVE_POSITION_TO";
// export const CONTEXT_TOPIC_RELATIVE_POSITION_ALONG = "CONTEXT_TOPIC_RELATIVE_POSITION_ALONG";

export const CONTEXT_TOPIC_RELATIVE_POSITION_WITH = "CONTEXT_TOPIC_RELATIVE_POSITION_WITH";

export const CONTEXT_TOPIC_RELATIVE_POSITION_BETWEEN = "CONTEXT_TOPIC_RELATIVE_POSITION_BETWEEN";
export const CONTEXT_TOPIC_RELATIVE_POSITION_ACROSS = "CONTEXT_TOPIC_RELATIVE_POSITION_ACROSS";
export const CONTEXT_TOPIC_RELATIVE_POSITION_THROUGH = "CONTEXT_TOPIC_RELATIVE_POSITION_THROUGH";

export const CONTEXT_TOPIC_RELATIVE_POSITION_INSIDE = "CONTEXT_TOPIC_RELATIVE_POSITION_INSIDE";
// export const PREP_POSITION_WITHIN = "PREP_POSITION_WITHIN";
// export const PREP_POSITION_IN = "PREP_POSITION_IN";
// export const PREP_POSITION_ON = "PT_POSITION_ON";
// export const PREP_DIRECTION_ONTO = "PREP_DIRECTION_ONTO";

export const CONTEXT_TOPIC_RELATIVE_POSITION_OUTSIDE = "CONTEXT_TOPIC_RELATIVE_POSITION_OUTSIDE";
// export const PREP_POSITION_OUT = "PREP_POSITION_OUT";


/* Context Direction */

export const CONTEXT_DIRECTION_IDLE = "CONTEXT_DIRECTION_IDLE";

export const CONTEXT_DIRECTION_TO = "CONTEXT_DIRECTION_TO";
// export const CONTEXT_DIRECTION_TOWARD = "CONTEXT_DIRECTION_TOWARD";

export const CONTEXT_DIRECTION_FROM = "CONTEXT_DIRECTION_FROM";
// export const CONTEXT_DIRECTION_AWAY = "CONTEXT_DIRECTION_AWAY";

export const CONTEXT_DIRECTION_ACROSS = "CONTEXT_DIRECTION_ACROSS";
// export const CONTEXT_DIRECTION_THROUGH = "CONTEXT_DIRECTION_THROUGH";


/* Context Agency */

export const CONTEXT_AGENCY_BY = "CONTEXT_AGENCY_BY";
export const CONTEXT_AGENCY_WITH = "CONTEXT_AGENCY_WITH";


/* Context Instrument */

export const CONTEXT_INSTRUMENT_BY = "CONTEXT_INSTRUMENT_BY";
export const CONTEXT_INSTRUMENT_WITH = "CONTEXT_INSTRUMENT_WITH";
export const CONTEXT_INSTRUMENT_ON = "CONTEXT_INSTRUMENT_ON";

/* Context Reason  */

// for 
// through
// because of 
// on account of
// from 


// /* Context Connection  */
// of 
// to 
// with 

// /* Context Origin */

// from 
// of 