

// word.preposition

export const PREPOSITION_TYPE_TIME = 'PREPOSITION_TYPE_TIME';
export const PREPOSITION_TYPE_PLACE = 'PREPOSITION_TYPE_PLACE';
export const PREPOSITION_TYPE_MOVEMENT = 'PREPOSITION_TYPE_MOVEMENT';
export const PREPOSITION_TYPE_MANNER = 'PREPOSITION_TYPE_MANNER';
export const PREPOSITION_TYPE_INSTRUMENT = 'PREPOSITION_TYPE_INSTRUMENT';  // agent
export const PREPOSITION_TYPE_MEASURE = 'PREPOSITION_TYPE_MEASURE';
export const PREPOSITION_TYPE_SOURCE = 'PREPOSITION_TYPE_SOURCE';
export const PREPOSITION_TYPE_POSSESSION = 'PREPOSITION_TYPE_POSSESSION';

export const prepositionArray = [
  PREPOSITION_TYPE_TIME,
  PREPOSITION_TYPE_PLACE,
  PREPOSITION_TYPE_MOVEMENT,
  PREPOSITION_TYPE_MANNER,
  PREPOSITION_TYPE_INSTRUMENT,
  PREPOSITION_TYPE_MEASURE,
  PREPOSITION_TYPE_SOURCE,
  PREPOSITION_TYPE_POSSESSION,
];

/* POSITION */

// on, in, at

// beside
export const PREP_POSITION_AT = "PT_POSITION_AT"; 
export const PREP_POSITION_BY = "PREP_POSITION_BY";
// export const PREP_POSITION_NEXT = "PREP_POSITION_NEXT";
// export const PREP_POSITION_TO = "PREP_POSITION_TO";
// export const PREP_POSITION_BESIDE = "PREP_POSITION_BESIDE";
// export const PREP_POSITION_ALONG = "PREP_POSITION_ALONG";

// above - below
export const PREP_POSITION_ABOVE = "PREP_POSITION_ABOVE";
// export const PREP_POSITION_OVER = "PREP_POSITION_OVER";
// export const PREP_POSITION_UP = "PREP_POSITION_UP";

export const PREP_POSITION_BELOW = "PREP_POSITION_BELOW";
// export const PREP_POSITION_UNDER = "PREP_POSITION_UNDER";
// export const PREP_POSITION_UNDERNEATH	= "PREP_POSITION_UNDERNEATH";
// export const PREP_POSITION_BENEATH = "PREP_POSITION_BENEATH";
// export const PREP_POSITION_DOWN = "PREP_POSITION_DOWN";

// behind - in front
export const PREP_POSITION_BEHIND = "PREP_POSITION_BEHIND";
export const PREP_POSITION_IN_FRONT = "PREP_POSITION_IN_FRONT";

// inside - outside
export const PREP_POSITION_INSIDE = "PREP_POSITION_INSIDE";
// export const PREP_POSITION_WITHIN = "PREP_POSITION_WITHIN";
// export const PREP_POSITION_IN = "PREP_POSITION_IN";
// export const PREP_POSITION_ON = "PT_POSITION_ON";
// export const PREP_DIRECTION_ONTO = "PREP_DIRECTION_ONTO";

export const PREP_POSITION_OUTSIDE = "PREP_POSITION_OUTSIDE";
// export const PREP_POSITION_OUT = "PREP_POSITION_OUT";

// with
export const PREP_POSITION_WITH = "PREP_POSITION_WITH";

// across
export const PREP_POSITION_ACROSS = "PREP_POSITION_ACROSS";
export const PREP_POSITION_THROUGH = "PREP_POSITION_THROUGH";

// between	
export const PREP_POSITION_BETWEEN = "PREP_POSITION_BETWEEN";

/* DIRECTION */

// to - from
export const PREP_DIRECTION_TO = "PREP_DIRECTION_TO";
// export const PREP_DIRECTION_TOWARD = "PREP_DIRECTION_TOWARD";

export const PREP_DIRECTION_FROM = "PREP_DIRECTION_FROM";
// export const PREP_DIRECTION_AWAY = "PREP_DIRECTION_AWAY";

// for
export const PREP_DIRECTION_FOR = "PREP_DIRECTION_FOR";


/* STATE */

// on - off
export const PREP_STATE_ON = "PREP_STATE_ON";
export const PREP_STATE_OFF = "PREP_STATE_OFF";

/* TIME */

// Date
export const PREP_TIME_DATE_ON = "PT_TIME_ON";
export const PREP_TIME_DATE_IN = "PT_TIME_IN";
export const PREP_TIME_DATE_AT = "PT_TIME_AT";

// Point of time
export const PREP_TIME_POINT_OF_TIME_SINCE = "PT_TIME_SINCE";
export const PREP_TIME_POINT_OF_TIME_BEFORE = "PT_TIME_BEFORE";
export const PREP_TIME_POINT_OF_TIME_AFTER = "PT_TIME_AFTER";
export const PREP_TIME_TIME_BY = "PT_TIME_BY";
export const PREP_TIME_TIME_AGO = "PT_TIME_AGO";

// Period of time
export const PREP_TIME_PERIOD_OF_TIME_FOR = "PT_TIME_FOR";
export const PREP_TIME_PERIOD_OF_TIME_TO = "PT_TIME_TO";
export const PREP_TIME_PERIOD_OF_TIME_TILL = "PT_TIME_TILL";
export const PREP_TIME_PERIOD_OF_TIME_UNTIL = "PT_TIME_UNTIL";

// Telling the time
export const PREP_TIME_TELL_TIME_TO = "PT_TIME_TO";
export const PREP_TIME_TELL_TIME_PAST = "PT_TIME_PAST";

// opposite	
// except

// -------

// during	
// without

