export const __TYPENAME_USER = '__TYPENAME_USER';

export const __TYPENAME_SENTENCE_DISPLAY_OPTIONS = '__TYPENAME_SENTENCE_DISPLAY_OPTIONS';
export const __TYPENAME_SENTENCE_STATS = '__TYPENAME_SENTENCE_STATS';
export const __TYPENAME_CONTROL_PANEL_OPTIONS = '__TYPENAME_CONTROL_PANEL_OPTIONS';
export const __TYPENAME_OPTIONS = '__TYPENAME_OPTIONS';
export const __TYPENAME_MODIFIERS = '__TYPENAME_MODIFIERS';

export const __TYPENAME_WORD_ELEMENT = '__TYPENAME_WORD_ELEMENT';
export const __TYPENAME_META = '__TYPENAME_META';
export const __TYPENAME_WORD = '__TYPENAME_WORD';
export const __TYPENAME_ENGLISH = '__TYPENAME_ENGLISH';
export const __TYPENAME_JAPANESE = '__TYPENAME_JAPANESE';

export const __TYPENAME_CONJUGATED_JAPANESE_VERB = '__TYPENAME_CONJUGATED_JAPANESE_VERB';
export const __TYPENAME_CONJUGATED_JAPANESE_NOUN = '__TYPENAME_CONJUGATED_JAPANESE_NOUN';
export const __TYPENAME_CONJUGATED_ENGLISH_NOUN = '__TYPENAME_CONJUGATED_ENGLISH_NOUN';
export const __TYPENAME_CONJUGATED_ENGLISH_VERB = '__TYPENAME_CONJUGATED_ENGLISH_VERB';
export const __TYPENAME_ENGLISH_JAPANESE_SENTENCE = '__TYPENAME_ENGLISH_JAPANESE_SENTENCE';
export const __TYPENAME_ENGLISH_JAPANESE_OPTIONS_SENTENCE = '__TYPENAME_ENGLISH_JAPANESE_OPTIONS_SENTENCE';
