export const __TYPENAME_USER = '__TYPENAME_USER';

export const __TYPENAME_SENTENCE_DISPLAY_OPTIONS = '__TYPENAME_SENTENCE_DISPLAY_OPTIONS';
export const __TYPENAME_SENTENCE_STATS = '__TYPENAME_SENTENCE_STATS';
export const __TYPENAME_CONTROL_PANEL_OPTIONS = '__TYPENAME_CONTROL_PANEL_OPTIONS';
export const __TYPENAME_OPTIONS = '__TYPENAME_OPTIONS';
export const __TYPENAME_MODIFIERS = '__TYPENAME_MODIFIERS';
export const __TYPENAME_SENTENCE_CONTEXT = '__TYPENAME_SENTENCE_CONTEXT';


export const __TYPENAME_WORD_ARRAY_ELEMENT = '__TYPENAME_WORD_ARRAY_ELEMENT';

export const __TYPENAME_NOUN = '__TYPENAME_NOUN';
export const __TYPENAME_VERB = '__TYPENAME_VERB';
export const __TYPENAME_ADJECTIVE = '__TYPENAME_ADJECTIVE';
export const __TYPENAME_ENGLISH_NOUN = '__TYPENAME_ENGLISH_NOUN';
export const __TYPENAME_JAPANESE_NOUN = '__TYPENAME_JAPANESE_NOUN';
export const __TYPENAME_ENGLISH_VERB = '__TYPENAME_ENGLISH_VERB';
export const __TYPENAME_JAPANESE_VERB = '__TYPENAME_JAPANESE_VERB';
export const __TYPENAME_ENGLISH_ADJECTIVE = '__TYPENAME_ENGLISH_ADJECTIVE';
export const __TYPENAME_JAPANESE_ADJECTIVE = '__TYPENAME_JAPANESE_ADJECTIVE';


export const __TYPENAME_CONJUGATED_JAPANESE_VERB = '__TYPENAME_CONJUGATED_JAPANESE_VERB';
export const __TYPENAME_CONJUGATED_JAPANESE_NOUN = '__TYPENAME_CONJUGATED_JAPANESE_NOUN';
export const __TYPENAME_CONJUGATED_ENGLISH_PREPOSITION = '__TYPENAME_CONJUGATED_ENGLISH_PREPOSITION';
export const __TYPENAME_CONJUGATED_ENGLISH_NOUN = '__TYPENAME_CONJUGATED_ENGLISH_NOUN';
export const __TYPENAME_CONJUGATED_ENGLISH_VERB = '__TYPENAME_CONJUGATED_ENGLISH_VERB';
export const __TYPENAME_ENGLISH_JAPANESE_SENTENCE = '__TYPENAME_ENGLISH_JAPANESE_SENTENCE';
export const __TYPENAME_ENGLISH_JAPANESE_OPTIONS_SENTENCE = '__TYPENAME_ENGLISH_JAPANESE_OPTIONS_SENTENCE';
