language: node_js
sudo: enabled

addons:
  ssh_known_hosts: 178.128.54.4

branches:
  only:
  - production

services:
  - docker

env:
  global:
  - secret: 4JtQSj0ehCD6B5BwyW6diVcaQA2c7bovI23GyeTTTgfkuKRkzDcoY51ZsMDdsflJ94zV7TEIS31eCeq4awftawft2IBYdHZeVZQlEQlUOfwD4B2XrAYXFIq1PAEiccakeskeriatwfuyoawfntarosenfwyoudmcUCykGm4bUZ3CaW6AxrIMFzuAYjA98VIz6YmYTmM0rst4gdh3y24rstrst
  - DOCKER_USERNAME=dottjt
  - secure: YydLAtHHczrVrZi7Pihf29ibPpLasX2pKXFVjS3alq30hIFjCclRB2KXXZdWFXuHnZY2xc8m6cRG/3bMpwM+RoOvWEPQfMXXPSj4Porez/iPjJ2bhlK48PVu5mB50iFt7QqF2IpV9HoC6yYIPvKzjTPCfrq9WhIyCxUiAi+PDiNGaKjeE8EvxgkAhIyUVjPAdyCoP1as8BezBzWWsIbOx2Ko1zBc4F3cAuo/McTUBFZCXZktlAVqov+6SwVNvsgcIINlyQ/BwJRum4IX+wCtQUkI6JTi03RcnaSv+z/aQsjZXf0B+gsvRKDFJifEyYW5VpZeb8Ab4zRjlYLyAtPBDqKpRydrnAeNNxUWVrr3x2NThnGd4YM0E7SJ+RCi4Cje2T/AOTlYkM+YCyyvMBlPdMBWCeIeC7nLUgcJBSmo89rskQBuTDEtXyVpvpXdpE4yCy6ipX1CysxzC1QrmeopYNYxtGAcl34RQXXiHZia09WR0kDX42394FJqvIK3gJWE2hk0s4OaDyTCovLCINDFW/2fPaSMXCAhKYYa63wecFFylyTYCuquUU0mxt9QejGrx0Ty7BYqu754sJdBwmVEu3yGb2jyMGE85dJWcqlkMDlFd6zAXTTnz3VyoSUoWBamAjRy/IHUaDEgPJYlxky0MAHZZbmRAoNutnDieU6Dpt8=

before_script:
  - docker pull dottjt/watashi-client || true
  - docker pull dottjt/watashi-nginx || true

script:
  - docker build --pull --cache-from dottjt/watashi-client -t dottjt/watashi-client
    ./watashi-client
  - docker run --rm -d dottjt/watashi-client
  - docker ps -a

  - docker build --pull --cache-from dottjt/watashi-nginx -t dottjt/watashi-nginx
    ./watashi-nginx
  - docker run --rm -d -p 80:80 dottjt/watashi-nginx
  - docker ps -a

after_script:
- docker images
- docker push dottjt/watashi-client
- docker push dottjt/watashi-nginx

before_deploy:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- openssl aes-256-cbc -K $encrypted_0aaf8c57bbc0_key -iv $encrypted_0aaf8c57bbc0_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  - provider: script
    script: bash infrastructure/scripts/deploy.sh
    on:
      branch: production
  - provider: script
    script: bash infrastructure/scripts/deploy.sh
    on:
      branch: production

