version: '3'
services:

  watashi-nginx-client:
    container_name: 'watashi-nginx-client'
    image: nginx:alpine
    build:
      context: ./watashi-client
      dockerfile: ./watashi-client/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    expose: 
      - 80
      - 443
    volumes:
      - ./production-site:/usr/share/nginx/html
      - ./dh-param:/etc/ssl/certs
      - /docker-volumes/etc/letsencrypt/live/ohhaithere.com/fullchain.pem:/etc/letsencrypt/live/ohhaithere.com/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/ohhaithere.com/privkey.pem:/etc/letsencrypt/live/ohhaithere.com/privkey.pem
      - /docker-volumes/data/letsencrypt:/data/letsencrypt
    networks:
      - docker-network
    restart: always
    depends_on:
      - client
      - postgres

networks:
  docker-network:
    driver: bridge


  # watashi-postgres:
  #   image: postgres:alpine
  #   ports:
  #     - 5432:5432
  #   expose: 
  #     - 5432
  #   volumes:
  #     - ./watashi-postgres:/var/lib/postgresql/data:rw
  #   restart: always

  # watashi-api:
  #   build:
  #     context: ./watashi-api
  #     dockerfile: ./infrastructure/docker/DockerfileAPI
  #   volumes:
  #     - ./watashi-api:/usr/src/app/api:rw
  #   ports:
  #     - 4000:4000
  #   expose: 
  #     - 4000
  #   depends_on:
  #     - nginx
  #     - postgres

