version: '3'
services:

  nginx:
    build:
      context: ./watashi-nginx
      dockerfile: ${PWD}/infrastructure/docker/DockerfileNginx
    ports:
      - 5000:80
    expose:
      - 80
    restart: always
    depends_on:
      - client

  client:
    build:
      context: ./watashi-client
      dockerfile: ${PWD}/infrastructure/docker/DockerfileClient
    ports:
      - 5000:5000

  # postgres:
  #   image: postgres:alpine
  #   ports:
  #     - 5432:5432
  #   expose: 
  #     - 5432
  #   volumes:
  #     - ./watashi-postgres:/var/lib/postgresql/data:rw
  #   restart: always

  # api:
  #   build:
  #     context: ./watashi-api
  #     dockerfile: ./infrastructure/docker/DockerfileAPI
  #   volumes:
  #     - ./watashi-api:/usr/src/app/api:rw
  #   ports:
  #     - 4000:4000
  #   expose: 
  #     - 4000
  #   depends_on:
  #     - nginx
  #     - postgres

