version: '3'
services:

  nginx-server: 
    image: nginx:alpine
    ports: 
      - 3030:80
    volumes: 
      - type: volume
        source: mydata
        target: /data
        volume:
          nocopy: true

  postgres:
    image: postgres:alpine
    expose: 
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
  
  server:
    build: .
    volumes:
      - .:/usr/src/app/server
    ports:
      - 3030:3030
    depends_on:
      - postgres

  client:
    build: client
    volumes:
      - ./client:/usr/src/app/client
    ports:
      - 3000:3000
    depends_on:
      - server      
