version: '3'
services:
  watashi-nginx:
    container_name: 'watashi-nginx'
    # image: nginx:alpine
    build:
      context: ./watashi-nginx
      dockerfile: ./watashi-nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    expose: 
      - 80
      - 443
    volumes:
      - ./production-site:/usr/share/nginx/html
      - ./dh-param:/etc/ssl/certs
      - /docker-volumes/etc/letsencrypt/live/watashiengine.com/fullchain.pem:/etc/letsencrypt/live/watashiengine.com/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/watashiengine.com/privkey.pem:/etc/letsencrypt/live/watashiengine.com/privkey.pem
      - /docker-volumes/data/letsencrypt:/data/letsencrypt
    networks:
      - docker-network
    restart: always
    # depends_on:
    #   - watashi-client
    #   - watashi-postgres

  watashi-client:
    container_name: 'watashi-client'
    build:
      context: ./watashi-client
      dockerfile: ./watashi-client/Dockerfile


networks:
  docker-network:
    driver: bridge


  # watashi-postgres:
  #   image: postgres:alpine
  #   ports:
  #     - 5432:5432
  #   expose: 
  #     - 5432
  #   volumes:
  #     - ./watashi-postgres:/var/lib/postgresql/data:rw
  #   restart: always

  # watashi-api:
  #   build:
  #     context: ./watashi-api
  #     dockerfile: ./infrastructure/docker/DockerfileAPI
  #   volumes:
  #     - ./watashi-api:/usr/src/app/api:rw
  #   ports:
  #     - 4000:4000
  #   expose: 
  #     - 4000
  #   depends_on:
  #     - nginx
  #     - postgres

