version: '3'
services:

  nginx-server: 
    image: nginx:alpine
    ports:
      - 3030:80
    volumes: 
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
      
  postgres:
    image: postgres:alpine
    expose: 
      - 5432
    volumes:
      - ./watashi-postgres:/var/lib/postgresql/data:rw
    restart: always
  
  server:
    build: .
    volumes:
      - ./watashi-server:/usr/src/app/server:rw
    ports:
      - 3030:3030
    depends_on:
      - postgres

  client:
    build: client
    volumes:
      - ./watashi-client:/usr/src/app/client:rw
    ports:
      - 3000:3000
    depends_on:
      - server      
