version: '3'
services:
  watashi-client:
    container_name: 'watashi-client'
    image: 'watashi-client'
    build:
      context: ./watashi-client

  # watashi-api:
  #   build:
  #     context: ./watashi-api
