version: '3'
services:

  nginx-server: 
    image: nginx:alpine
    ports:
      - 5000:80
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:rw

  postgres:
    image: postgres:alpine
    expose: 
      - 5432
    volumes:
      - ./watashi-postgres:/var/lib/postgresql/data:rw
    restart: always
  
  api:
    build: .
    volumes:
      - ./watashi-api:/usr/src/app/api:rw
    ports:
      - 3030:3030
    depends_on:
      - postgres

  client:
    build: client
    volumes:
      - ./watashi-client:/usr/src/app/client:rw
    ports:
      - 5000:5000
    depends_on:
      - server      
