import {
  LESSON_TITLE,
  LESSON_DESCRIPTION,
  LESSON_EXPLANATION,
  LESSON_RESOURCES,
} from './descriptionConfig';

import {
  LESSON_TOPIC_INTENT,
  LESSON_PROXIMITY,
  LESSON_TOPIC_DESTINATION,
  LESSON_DIRECTION,
  LESSON_EVENT_OCCURANCE,
  LESSON_EVENT_DURATION,
  LESSON_POV,
  LESSON_SUBJECT_CONNECTION,
  LESSON_SUBJECT_ROLE,
  LESSON_SUBJECT_QUANTITY,
} from './contextConfig';

import {
  LESSON_PRE_OPTIONS,
} from './optionsConfig';

import {
  LESSON_PRE_MODIFIERS,
} from './modifiersConfig';

import {
  __TYPENAME_SENTENCE_CONTEXT,
} from '../constants/typeNameConstants';



export const L001 = {
  LESSON_TITLE: LESSON_TITLE.L001 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L001 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L001 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L001 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L001 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L001 as Util.PreModifiers,
};

export const L002 = {
  LESSON_TITLE: LESSON_TITLE.L002 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L002 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L002 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L002 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L002 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L002 as Util.PreModifiers,
};

export const L003 = {
  LESSON_TITLE: LESSON_TITLE.L003 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L003 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L003 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L003 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L003 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L003 as Util.PreModifiers,
};

export const L004 = {
  LESSON_TITLE: LESSON_TITLE.L004 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L004 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L004 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L004 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L004 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L004 as Util.PreModifiers,
};

export const L005 = {
  LESSON_TITLE: LESSON_TITLE.L005 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L005 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L005 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L005 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L005 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L005 as Util.PreModifiers,
};

export const L006 = {
  LESSON_TITLE: LESSON_TITLE.L006 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L006 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L006 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L006 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L006 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L006 as Util.PreModifiers,
};

export const L007 = {
  LESSON_TITLE: LESSON_TITLE.L007 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L007 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L007 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L007 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L007 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L007 as Util.PreModifiers,
};

export const L008 = {
  LESSON_TITLE: LESSON_TITLE.L008 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L008 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L008 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L008 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L008 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L008 as Util.PreModifiers,
};

export const L009 = {
  LESSON_TITLE: LESSON_TITLE.L009 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L009 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L009 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L009 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L009 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L009 as Util.PreModifiers,
};

export const L010 = {
  LESSON_TITLE: LESSON_TITLE.L010 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L010 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L010 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L010 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L010 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L010 as Util.PreModifiers,
};

export const L011 = {
  LESSON_TITLE: LESSON_TITLE.L011 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L011 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L011 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L011 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L011 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L011 as Util.PreModifiers,
};

export const L012 = {
  LESSON_TITLE: LESSON_TITLE.L012 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L012 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L012 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L012 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L012 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L012 as Util.PreModifiers,
};

export const L013 = {
  LESSON_TITLE: LESSON_TITLE.L013 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L013 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L013 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L013 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L013 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L013 as Util.PreModifiers,
};

export const L014 = {
  LESSON_TITLE: LESSON_TITLE.L014 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L014 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L014 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L014 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L014 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L014 as Util.PreModifiers,
};

export const L015 = {
  LESSON_TITLE: LESSON_TITLE.L015 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L015 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L015 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L015 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L015 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L015 as Util.PreModifiers,
};

export const L016 = {
  LESSON_TITLE: LESSON_TITLE.L016 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L016 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L016 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L016 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L016 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L016 as Util.PreModifiers,
};

export const L017 = {
  LESSON_TITLE: LESSON_TITLE.L017 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L017 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L017 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L017 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L017 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L017 as Util.PreModifiers,
};

export const L018 = {
  LESSON_TITLE: LESSON_TITLE.L018 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L018 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L018 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L018 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L018 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L018 as Util.PreModifiers,
};

export const L019 = {
  LESSON_TITLE: LESSON_TITLE.L019 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L019 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L019 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L019 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L019 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L019 as Util.PreModifiers,
}

export const L020 = {
  LESSON_TITLE: LESSON_TITLE.L020 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L020 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L020 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L020 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L020 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L020 as Util.PreModifiers,
}

export const LESSON_PRE_SENTENCE_CONTEXT = {
  L001: { topicIntentArray: LESSON_TOPIC_INTENT.L001, topicProximityArray: LESSON_PROXIMITY.L001, topicDestinationArray: LESSON_TOPIC_DESTINATION.L001, eventDirectionArray: LESSON_DIRECTION.L001, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L001, eventDurationArray: LESSON_EVENT_DURATION.L001, eventPOVArray: LESSON_POV.L001, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L001, subjectRoleArray: LESSON_SUBJECT_ROLE.L001, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L001, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.PreSentenceContext, // T
  L002: { topicIntentArray: LESSON_TOPIC_INTENT.L002, topicProximityArray: LESSON_PROXIMITY.L002, topicDestinationArray: LESSON_TOPIC_DESTINATION.L002, eventDirectionArray: LESSON_DIRECTION.L002, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L002, eventDurationArray: LESSON_EVENT_DURATION.L002, eventPOVArray: LESSON_POV.L002, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L002, subjectRoleArray: LESSON_SUBJECT_ROLE.L002, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L002, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.PreSentenceContext, // WA_TS, MO_TS
  L003: { topicIntentArray: LESSON_TOPIC_INTENT.L003, topicProximityArray: LESSON_PROXIMITY.L003, topicDestinationArray: LESSON_TOPIC_DESTINATION.L003, eventDirectionArray: LESSON_DIRECTION.L003, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L003, eventDurationArray: LESSON_EVENT_DURATION.L003, eventPOVArray: LESSON_POV.L003, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L003, subjectRoleArray: LESSON_SUBJECT_ROLE.L003, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L003, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.PreSentenceContext, // GA_TS
  L004: { topicIntentArray: LESSON_TOPIC_INTENT.L004, topicProximityArray: LESSON_PROXIMITY.L004, topicDestinationArray: LESSON_TOPIC_DESTINATION.L004, eventDirectionArray: LESSON_DIRECTION.L004, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L004, eventDurationArray: LESSON_EVENT_DURATION.L004, eventPOVArray: LESSON_POV.L004, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L004, subjectRoleArray: LESSON_SUBJECT_ROLE.L004, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L004, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.PreSentenceContext, // WA_TS, GA_TS
  L005: { topicIntentArray: LESSON_TOPIC_INTENT.L005, topicProximityArray: LESSON_PROXIMITY.L005, topicDestinationArray: LESSON_TOPIC_DESTINATION.L005, eventDirectionArray: LESSON_DIRECTION.L005, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L005, eventDurationArray: LESSON_EVENT_DURATION.L005, eventPOVArray: LESSON_POV.L005, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L005, subjectRoleArray: LESSON_SUBJECT_ROLE.L005, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L005, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.PreSentenceContext, // WA_TS, MO_TS, GA_TS
  L006: { topicIntentArray: LESSON_TOPIC_INTENT.L006, topicProximityArray: LESSON_PROXIMITY.L006, topicDestinationArray: LESSON_TOPIC_DESTINATION.L006, eventDirectionArray: LESSON_DIRECTION.L006, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L006, eventDurationArray: LESSON_EVENT_DURATION.L006, eventPOVArray: LESSON_POV.L006, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L006, subjectRoleArray: LESSON_SUBJECT_ROLE.L006, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L006, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.PreSentenceContext, // V
  L007: { topicIntentArray: LESSON_TOPIC_INTENT.L007, topicProximityArray: LESSON_PROXIMITY.L007, topicDestinationArray: LESSON_TOPIC_DESTINATION.L007, eventDirectionArray: LESSON_DIRECTION.L007, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L007, eventDurationArray: LESSON_EVENT_DURATION.L007, eventPOVArray: LESSON_POV.L007, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L007, subjectRoleArray: LESSON_SUBJECT_ROLE.L007, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L007, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.PreSentenceContext, // V
  L008: { topicIntentArray: LESSON_TOPIC_INTENT.L008, topicProximityArray: LESSON_PROXIMITY.L008, topicDestinationArray: LESSON_TOPIC_DESTINATION.L008, eventDirectionArray: LESSON_DIRECTION.L008, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L008, eventDurationArray: LESSON_EVENT_DURATION.L008, eventPOVArray: LESSON_POV.L008, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L008, subjectRoleArray: LESSON_SUBJECT_ROLE.L008, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L008, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.PreSentenceContext, // V
  L009: { topicIntentArray: LESSON_TOPIC_INTENT.L009, topicProximityArray: LESSON_PROXIMITY.L009, topicDestinationArray: LESSON_TOPIC_DESTINATION.L009, eventDirectionArray: LESSON_DIRECTION.L009, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L009, eventDurationArray: LESSON_EVENT_DURATION.L009, eventPOVArray: LESSON_POV.L009, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L009, subjectRoleArray: LESSON_SUBJECT_ROLE.L009, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L009, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.PreSentenceContext, // WO_SV
  L010: { topicIntentArray: LESSON_TOPIC_INTENT.L010, topicProximityArray: LESSON_PROXIMITY.L010, topicDestinationArray: LESSON_TOPIC_DESTINATION.L010, eventDirectionArray: LESSON_DIRECTION.L010, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L010, eventDurationArray: LESSON_EVENT_DURATION.L010, eventPOVArray: LESSON_POV.L010, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L010, subjectRoleArray: LESSON_SUBJECT_ROLE.L010, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L010, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.PreSentenceContext, // NI_SV
  L011: { topicIntentArray: LESSON_TOPIC_INTENT.L011, topicProximityArray: LESSON_PROXIMITY.L011, topicDestinationArray: LESSON_TOPIC_DESTINATION.L011, eventDirectionArray: LESSON_DIRECTION.L011, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L011, eventDurationArray: LESSON_EVENT_DURATION.L011, eventPOVArray: LESSON_POV.L011, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L011, subjectRoleArray: LESSON_SUBJECT_ROLE.L011, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L011, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.PreSentenceContext, // DE_SV
  L012: { topicIntentArray: LESSON_TOPIC_INTENT.L012, topicProximityArray: LESSON_PROXIMITY.L012, topicDestinationArray: LESSON_TOPIC_DESTINATION.L012, eventDirectionArray: LESSON_DIRECTION.L012, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L012, eventDurationArray: LESSON_EVENT_DURATION.L012, eventPOVArray: LESSON_POV.L012, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L012, subjectRoleArray: LESSON_SUBJECT_ROLE.L012, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L012, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.PreSentenceContext, // WO_SV, NI_SV
  L013: { topicIntentArray: LESSON_TOPIC_INTENT.L013, topicProximityArray: LESSON_PROXIMITY.L013, topicDestinationArray: LESSON_TOPIC_DESTINATION.L013, eventDirectionArray: LESSON_DIRECTION.L013, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L013, eventDurationArray: LESSON_EVENT_DURATION.L013, eventPOVArray: LESSON_POV.L013, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L013, subjectRoleArray: LESSON_SUBJECT_ROLE.L013, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L013, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.PreSentenceContext, // NI_SV, DE_SV
  L014: { topicIntentArray: LESSON_TOPIC_INTENT.L014, topicProximityArray: LESSON_PROXIMITY.L014, topicDestinationArray: LESSON_TOPIC_DESTINATION.L014, eventDirectionArray: LESSON_DIRECTION.L014, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L014, eventDurationArray: LESSON_EVENT_DURATION.L014, eventPOVArray: LESSON_POV.L014, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L014, subjectRoleArray: LESSON_SUBJECT_ROLE.L014, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L014, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.PreSentenceContext, // DE_SV, WO_SV
  L015: { topicIntentArray: LESSON_TOPIC_INTENT.L015, topicProximityArray: LESSON_PROXIMITY.L015, topicDestinationArray: LESSON_TOPIC_DESTINATION.L015, eventDirectionArray: LESSON_DIRECTION.L015, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L015, eventDurationArray: LESSON_EVENT_DURATION.L015, eventPOVArray: LESSON_POV.L015, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L015, subjectRoleArray: LESSON_SUBJECT_ROLE.L015, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L015, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.PreSentenceContext, // WO_SV, NI_SV, DE_SV
  L016: { topicIntentArray: LESSON_TOPIC_INTENT.L016, topicProximityArray: LESSON_PROXIMITY.L016, topicDestinationArray: LESSON_TOPIC_DESTINATION.L016, eventDirectionArray: LESSON_DIRECTION.L016, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L016, eventDurationArray: LESSON_EVENT_DURATION.L016, eventPOVArray: LESSON_POV.L016, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L016, subjectRoleArray: LESSON_SUBJECT_ROLE.L016, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L016, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.PreSentenceContext, // KARA_SV
  L017: { topicIntentArray: LESSON_TOPIC_INTENT.L017, topicProximityArray: LESSON_PROXIMITY.L017, topicDestinationArray: LESSON_TOPIC_DESTINATION.L017, eventDirectionArray: LESSON_DIRECTION.L017, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L017, eventDurationArray: LESSON_EVENT_DURATION.L017, eventPOVArray: LESSON_POV.L017, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L017, subjectRoleArray: LESSON_SUBJECT_ROLE.L017, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L017, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.PreSentenceContext, // MADE_SV
  L018: { topicIntentArray: LESSON_TOPIC_INTENT.L018, topicProximityArray: LESSON_PROXIMITY.L018, topicDestinationArray: LESSON_TOPIC_DESTINATION.L018, eventDirectionArray: LESSON_DIRECTION.L018, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L018, eventDurationArray: LESSON_EVENT_DURATION.L018, eventPOVArray: LESSON_POV.L018, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L018, subjectRoleArray: LESSON_SUBJECT_ROLE.L018, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L018, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.PreSentenceContext, // NA - T_NO
  L019: { topicIntentArray: LESSON_TOPIC_INTENT.L019, topicProximityArray: LESSON_PROXIMITY.L019, topicDestinationArray: LESSON_TOPIC_DESTINATION.L019, eventDirectionArray: LESSON_DIRECTION.L019, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L019, eventDurationArray: LESSON_EVENT_DURATION.L019, eventPOVArray: LESSON_POV.L019, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L019, subjectRoleArray: LESSON_SUBJECT_ROLE.L019, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L019, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.PreSentenceContext, // T - T_ADJ
  L020: { topicIntentArray: LESSON_TOPIC_INTENT.L020, topicProximityArray: LESSON_PROXIMITY.L020, topicDestinationArray: LESSON_TOPIC_DESTINATION.L020, eventDirectionArray: LESSON_DIRECTION.L020, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L020, eventDurationArray: LESSON_EVENT_DURATION.L020, eventPOVArray: LESSON_POV.L020, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L020, subjectRoleArray: LESSON_SUBJECT_ROLE.L020, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L020, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.PreSentenceContext, // T - T_ADV
  // L021:
  // L022: 
  // L023: 
  // L024: 
  // L025: 
  // L026: 
  // L027: 
};




