import {
  LESSON_TITLE,
  LESSON_DESCRIPTION,
  LESSON_EXPLANATION,
  LESSON_RESOURCES,
} from './descriptionConfig';

import {
  LESSON_TOPIC_INTENT,
  LESSON_PROXIMITY,
  LESSON_TOPIC_DESTINATION,
  LESSON_DIRECTION,
  LESSON_EVENT_OCCURANCE,
  LESSON_EVENT_DURATION,
  LESSON_POV,
  LESSON_SUBJECT_CONNECTION,
  LESSON_SUBJECT_ROLE,
  LESSON_SUBJECT_QUANTITY,
} from './contextConfig';

import {
  LESSON_OPTIONS,
} from './optionsConfig';

import {
  LESSON_MODIFIERS,
} from './modifiersConfig';

import {
  __TYPENAME_SENTENCE_CONTEXT,
} from '../constants/typeNameConstants';



export const L001 = {
  LESSON_TITLE: LESSON_TITLE.L001,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L001,
  LESSON_OPTIONS: LESSON_OPTIONS.L001,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L001,
  LESSON_RESOURCES: LESSON_RESOURCES.L001,
  LESSON_MODIFIERS: LESSON_MODIFIERS.L001,
};

export const L002 = {
  LESSON_TITLE: LESSON_TITLE.L002,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L002,
  LESSON_OPTIONS: LESSON_OPTIONS.L002,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L002,
  LESSON_RESOURCES: LESSON_RESOURCES.L002,
  LESSON_MODIFIERS: LESSON_MODIFIERS.L002,
};

export const L003 = {
  LESSON_TITLE: LESSON_TITLE.L003,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L003,
  LESSON_OPTIONS: LESSON_OPTIONS.L003,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L003,
  LESSON_RESOURCES: LESSON_RESOURCES.L003,
  LESSON_MODIFIERS: LESSON_MODIFIERS.L003,
};

export const L004 = {
  LESSON_TITLE: LESSON_TITLE.L004,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L004,
  LESSON_OPTIONS: LESSON_OPTIONS.L004,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L004,
  LESSON_RESOURCES: LESSON_RESOURCES.L004,
  LESSON_MODIFIERS: LESSON_MODIFIERS.L004,
};

export const L005 = {
  LESSON_TITLE: LESSON_TITLE.L005,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L005,
  LESSON_OPTIONS: LESSON_OPTIONS.L005,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L005,
  LESSON_RESOURCES: LESSON_RESOURCES.L005,
  LESSON_MODIFIERS: LESSON_MODIFIERS.L005,
};

export const L006 = {
  LESSON_TITLE: LESSON_TITLE.L006,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L006,
  LESSON_OPTIONS: LESSON_OPTIONS.L006,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L006,
  LESSON_RESOURCES: LESSON_RESOURCES.L006,
  LESSON_MODIFIERS: LESSON_MODIFIERS.L006,
};

export const L007 = {
  LESSON_TITLE: LESSON_TITLE.L007,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L007,
  LESSON_OPTIONS: LESSON_OPTIONS.L007,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L007,
  LESSON_RESOURCES: LESSON_RESOURCES.L007,
  LESSON_MODIFIERS: LESSON_MODIFIERS.L007,
};

export const L008 = {
  LESSON_TITLE: LESSON_TITLE.L008,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L008,
  LESSON_OPTIONS: LESSON_OPTIONS.L008,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L008,
  LESSON_RESOURCES: LESSON_RESOURCES.L008,
  LESSON_MODIFIERS: LESSON_MODIFIERS.L008,
};

export const L009 = {
  LESSON_TITLE: LESSON_TITLE.L009,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L009,
  LESSON_OPTIONS: LESSON_OPTIONS.L009,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L009,
  LESSON_RESOURCES: LESSON_RESOURCES.L009,
  LESSON_MODIFIERS: LESSON_MODIFIERS.L009,
};

export const L010 = {
  LESSON_TITLE: LESSON_TITLE.L010,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L010,
  LESSON_OPTIONS: LESSON_OPTIONS.L010,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L010,
  LESSON_RESOURCES: LESSON_RESOURCES.L010,
  LESSON_MODIFIERS: LESSON_MODIFIERS.L010,
};

export const L011 = {
  LESSON_TITLE: LESSON_TITLE.L011,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L011,
  LESSON_OPTIONS: LESSON_OPTIONS.L011,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L011,
  LESSON_RESOURCES: LESSON_RESOURCES.L011,
  LESSON_MODIFIERS: LESSON_MODIFIERS.L011,
};

export const L012 = {
  LESSON_TITLE: LESSON_TITLE.L012,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L012,
  LESSON_OPTIONS: LESSON_OPTIONS.L012,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L012,
  LESSON_RESOURCES: LESSON_RESOURCES.L012,
  LESSON_MODIFIERS: LESSON_MODIFIERS.L012,
};

export const L013 = {
  LESSON_TITLE: LESSON_TITLE.L013,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L013,
  LESSON_OPTIONS: LESSON_OPTIONS.L013,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L013,
  LESSON_RESOURCES: LESSON_RESOURCES.L013,
  LESSON_MODIFIERS: LESSON_MODIFIERS.L013,
};

export const L014 = {
  LESSON_TITLE: LESSON_TITLE.L014,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L014,
  LESSON_OPTIONS: LESSON_OPTIONS.L014,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L014,
  LESSON_RESOURCES: LESSON_RESOURCES.L014,
  LESSON_MODIFIERS: LESSON_MODIFIERS.L014,
};

export const L015 = {
  LESSON_TITLE: LESSON_TITLE.L015,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L015,
  LESSON_OPTIONS: LESSON_OPTIONS.L015,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L015,
  LESSON_RESOURCES: LESSON_RESOURCES.L015,
  LESSON_MODIFIERS: LESSON_MODIFIERS.L015,
};

export const L016 = {
  LESSON_TITLE: LESSON_TITLE.L016,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L016,
  LESSON_OPTIONS: LESSON_OPTIONS.L016,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L016,
  LESSON_RESOURCES: LESSON_RESOURCES.L016,
  LESSON_MODIFIERS: LESSON_MODIFIERS.L016,
};

export const L017 = {
  LESSON_TITLE: LESSON_TITLE.L017,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L017,
  LESSON_OPTIONS: LESSON_OPTIONS.L017,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L017,
  LESSON_RESOURCES: LESSON_RESOURCES.L017,
  LESSON_MODIFIERS: LESSON_MODIFIERS.L017,
};

export const L018 = {
  LESSON_TITLE: LESSON_TITLE.L018,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L018,
  LESSON_OPTIONS: LESSON_OPTIONS.L018,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L018,
  LESSON_RESOURCES: LESSON_RESOURCES.L018,
  LESSON_MODIFIERS: LESSON_MODIFIERS.L018,
};

export const L019 = {
  LESSON_TITLE: LESSON_TITLE.L019,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L019,
  LESSON_OPTIONS: LESSON_OPTIONS.L019,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L019,
  LESSON_RESOURCES: LESSON_RESOURCES.L019,
};

export const L020 = {
  LESSON_TITLE: LESSON_TITLE.L020,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L020,
  LESSON_OPTIONS: LESSON_OPTIONS.L020,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L020,
  LESSON_RESOURCES: LESSON_RESOURCES.L020,
};

export const LESSON_SENTENCE_CONTEXT = {
  L001: { topicIntent: LESSON_TOPIC_INTENT.L001, topicProximity: LESSON_PROXIMITY.L001, topicDestination: LESSON_TOPIC_DESTINATION.L001, eventDirection: LESSON_DIRECTION.L001, eventOccurance: LESSON_EVENT_OCCURANCE.L001, eventDuration: LESSON_EVENT_DURATION.L001, eventPOV: LESSON_POV.L001, subjectConnection: LESSON_SUBJECT_CONNECTION.L001, subjectRole: LESSON_SUBJECT_ROLE.L001, subjectQuantity: LESSON_SUBJECT_QUANTITY.L001, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.SentenceContext, // T
  L002: { topicIntent: LESSON_TOPIC_INTENT.L002, topicProximity: LESSON_PROXIMITY.L002, topicDestination: LESSON_TOPIC_DESTINATION.L002, eventDirection: LESSON_DIRECTION.L002, eventOccurance: LESSON_EVENT_OCCURANCE.L002, eventDuration: LESSON_EVENT_DURATION.L002, eventPOV: LESSON_POV.L002, subjectConnection: LESSON_SUBJECT_CONNECTION.L002, subjectRole: LESSON_SUBJECT_ROLE.L002, subjectQuantity: LESSON_SUBJECT_QUANTITY.L002, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.SentenceContext, // WA_TS, MO_TS
  L003: { topicIntent: LESSON_TOPIC_INTENT.L003, topicProximity: LESSON_PROXIMITY.L003, topicDestination: LESSON_TOPIC_DESTINATION.L003, eventDirection: LESSON_DIRECTION.L003, eventOccurance: LESSON_EVENT_OCCURANCE.L003, eventDuration: LESSON_EVENT_DURATION.L003, eventPOV: LESSON_POV.L003, subjectConnection: LESSON_SUBJECT_CONNECTION.L003, subjectRole: LESSON_SUBJECT_ROLE.L003, subjectQuantity: LESSON_SUBJECT_QUANTITY.L003, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.SentenceContext, // GA_TS
  L004: { topicIntent: LESSON_TOPIC_INTENT.L004, topicProximity: LESSON_PROXIMITY.L004, topicDestination: LESSON_TOPIC_DESTINATION.L004, eventDirection: LESSON_DIRECTION.L004, eventOccurance: LESSON_EVENT_OCCURANCE.L004, eventDuration: LESSON_EVENT_DURATION.L004, eventPOV: LESSON_POV.L004, subjectConnection: LESSON_SUBJECT_CONNECTION.L004, subjectRole: LESSON_SUBJECT_ROLE.L004, subjectQuantity: LESSON_SUBJECT_QUANTITY.L004, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.SentenceContext, // WA_TS, GA_TS
  L005: { topicIntent: LESSON_TOPIC_INTENT.L005, topicProximity: LESSON_PROXIMITY.L005, topicDestination: LESSON_TOPIC_DESTINATION.L005, eventDirection: LESSON_DIRECTION.L005, eventOccurance: LESSON_EVENT_OCCURANCE.L005, eventDuration: LESSON_EVENT_DURATION.L005, eventPOV: LESSON_POV.L005, subjectConnection: LESSON_SUBJECT_CONNECTION.L005, subjectRole: LESSON_SUBJECT_ROLE.L005, subjectQuantity: LESSON_SUBJECT_QUANTITY.L005, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.SentenceContext, // WA_TS, MO_TS, GA_TS
  L006: { topicIntent: LESSON_TOPIC_INTENT.L006, topicProximity: LESSON_PROXIMITY.L006, topicDestination: LESSON_TOPIC_DESTINATION.L006, eventDirection: LESSON_DIRECTION.L006, eventOccurance: LESSON_EVENT_OCCURANCE.L006, eventDuration: LESSON_EVENT_DURATION.L006, eventPOV: LESSON_POV.L006, subjectConnection: LESSON_SUBJECT_CONNECTION.L006, subjectRole: LESSON_SUBJECT_ROLE.L006, subjectQuantity: LESSON_SUBJECT_QUANTITY.L006, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.SentenceContext, // V
  L007: { topicIntent: LESSON_TOPIC_INTENT.L007, topicProximity: LESSON_PROXIMITY.L007, topicDestination: LESSON_TOPIC_DESTINATION.L007, eventDirection: LESSON_DIRECTION.L007, eventOccurance: LESSON_EVENT_OCCURANCE.L007, eventDuration: LESSON_EVENT_DURATION.L007, eventPOV: LESSON_POV.L007, subjectConnection: LESSON_SUBJECT_CONNECTION.L007, subjectRole: LESSON_SUBJECT_ROLE.L007, subjectQuantity: LESSON_SUBJECT_QUANTITY.L007, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.SentenceContext, // V
  L008: { topicIntent: LESSON_TOPIC_INTENT.L008, topicProximity: LESSON_PROXIMITY.L008, topicDestination: LESSON_TOPIC_DESTINATION.L008, eventDirection: LESSON_DIRECTION.L008, eventOccurance: LESSON_EVENT_OCCURANCE.L008, eventDuration: LESSON_EVENT_DURATION.L008, eventPOV: LESSON_POV.L008, subjectConnection: LESSON_SUBJECT_CONNECTION.L008, subjectRole: LESSON_SUBJECT_ROLE.L008, subjectQuantity: LESSON_SUBJECT_QUANTITY.L008, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.SentenceContext, // V
  L009: { topicIntent: LESSON_TOPIC_INTENT.L009, topicProximity: LESSON_PROXIMITY.L009, topicDestination: LESSON_TOPIC_DESTINATION.L009, eventDirection: LESSON_DIRECTION.L009, eventOccurance: LESSON_EVENT_OCCURANCE.L009, eventDuration: LESSON_EVENT_DURATION.L009, eventPOV: LESSON_POV.L009, subjectConnection: LESSON_SUBJECT_CONNECTION.L009, subjectRole: LESSON_SUBJECT_ROLE.L009, subjectQuantity: LESSON_SUBJECT_QUANTITY.L009, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.SentenceContext, // WO_SV
  L010: { topicIntent: LESSON_TOPIC_INTENT.L010, topicProximity: LESSON_PROXIMITY.L010, topicDestination: LESSON_TOPIC_DESTINATION.L010, eventDirection: LESSON_DIRECTION.L010, eventOccurance: LESSON_EVENT_OCCURANCE.L010, eventDuration: LESSON_EVENT_DURATION.L010, eventPOV: LESSON_POV.L010, subjectConnection: LESSON_SUBJECT_CONNECTION.L010, subjectRole: LESSON_SUBJECT_ROLE.L010, subjectQuantity: LESSON_SUBJECT_QUANTITY.L010, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.SentenceContext, // NI_SV
  L011: { topicIntent: LESSON_TOPIC_INTENT.L011, topicProximity: LESSON_PROXIMITY.L011, topicDestination: LESSON_TOPIC_DESTINATION.L011, eventDirection: LESSON_DIRECTION.L011, eventOccurance: LESSON_EVENT_OCCURANCE.L011, eventDuration: LESSON_EVENT_DURATION.L011, eventPOV: LESSON_POV.L011, subjectConnection: LESSON_SUBJECT_CONNECTION.L011, subjectRole: LESSON_SUBJECT_ROLE.L011, subjectQuantity: LESSON_SUBJECT_QUANTITY.L011, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.SentenceContext, // DE_SV
  L012: { topicIntent: LESSON_TOPIC_INTENT.L012, topicProximity: LESSON_PROXIMITY.L012, topicDestination: LESSON_TOPIC_DESTINATION.L012, eventDirection: LESSON_DIRECTION.L012, eventOccurance: LESSON_EVENT_OCCURANCE.L012, eventDuration: LESSON_EVENT_DURATION.L012, eventPOV: LESSON_POV.L012, subjectConnection: LESSON_SUBJECT_CONNECTION.L012, subjectRole: LESSON_SUBJECT_ROLE.L012, subjectQuantity: LESSON_SUBJECT_QUANTITY.L012, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.SentenceContext, // WO_SV, NI_SV
  L013: { topicIntent: LESSON_TOPIC_INTENT.L013, topicProximity: LESSON_PROXIMITY.L013, topicDestination: LESSON_TOPIC_DESTINATION.L013, eventDirection: LESSON_DIRECTION.L013, eventOccurance: LESSON_EVENT_OCCURANCE.L013, eventDuration: LESSON_EVENT_DURATION.L013, eventPOV: LESSON_POV.L013, subjectConnection: LESSON_SUBJECT_CONNECTION.L013, subjectRole: LESSON_SUBJECT_ROLE.L013, subjectQuantity: LESSON_SUBJECT_QUANTITY.L013, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.SentenceContext, // NI_SV, DE_SV
  L014: { topicIntent: LESSON_TOPIC_INTENT.L014, topicProximity: LESSON_PROXIMITY.L014, topicDestination: LESSON_TOPIC_DESTINATION.L014, eventDirection: LESSON_DIRECTION.L014, eventOccurance: LESSON_EVENT_OCCURANCE.L014, eventDuration: LESSON_EVENT_DURATION.L014, eventPOV: LESSON_POV.L014, subjectConnection: LESSON_SUBJECT_CONNECTION.L014, subjectRole: LESSON_SUBJECT_ROLE.L014, subjectQuantity: LESSON_SUBJECT_QUANTITY.L014, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.SentenceContext, // DE_SV, WO_SV
  L015: { topicIntent: LESSON_TOPIC_INTENT.L015, topicProximity: LESSON_PROXIMITY.L015, topicDestination: LESSON_TOPIC_DESTINATION.L015, eventDirection: LESSON_DIRECTION.L015, eventOccurance: LESSON_EVENT_OCCURANCE.L015, eventDuration: LESSON_EVENT_DURATION.L015, eventPOV: LESSON_POV.L015, subjectConnection: LESSON_SUBJECT_CONNECTION.L015, subjectRole: LESSON_SUBJECT_ROLE.L015, subjectQuantity: LESSON_SUBJECT_QUANTITY.L015, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.SentenceContext, // WO_SV, NI_SV, DE_SV
  L016: { topicIntent: LESSON_TOPIC_INTENT.L016, topicProximity: LESSON_PROXIMITY.L016, topicDestination: LESSON_TOPIC_DESTINATION.L016, eventDirection: LESSON_DIRECTION.L016, eventOccurance: LESSON_EVENT_OCCURANCE.L016, eventDuration: LESSON_EVENT_DURATION.L016, eventPOV: LESSON_POV.L016, subjectConnection: LESSON_SUBJECT_CONNECTION.L016, subjectRole: LESSON_SUBJECT_ROLE.L016, subjectQuantity: LESSON_SUBJECT_QUANTITY.L016, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.SentenceContext, // KARA_SV
  L017: { topicIntent: LESSON_TOPIC_INTENT.L017, topicProximity: LESSON_PROXIMITY.L017, topicDestination: LESSON_TOPIC_DESTINATION.L017, eventDirection: LESSON_DIRECTION.L017, eventOccurance: LESSON_EVENT_OCCURANCE.L017, eventDuration: LESSON_EVENT_DURATION.L017, eventPOV: LESSON_POV.L017, subjectConnection: LESSON_SUBJECT_CONNECTION.L017, subjectRole: LESSON_SUBJECT_ROLE.L017, subjectQuantity: LESSON_SUBJECT_QUANTITY.L017, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.SentenceContext, // MADE_SV
  L018: { topicIntent: LESSON_TOPIC_INTENT.L018, topicProximity: LESSON_PROXIMITY.L018, topicDestination: LESSON_TOPIC_DESTINATION.L018, eventDirection: LESSON_DIRECTION.L018, eventOccurance: LESSON_EVENT_OCCURANCE.L018, eventDuration: LESSON_EVENT_DURATION.L018, eventPOV: LESSON_POV.L018, subjectConnection: LESSON_SUBJECT_CONNECTION.L018, subjectRole: LESSON_SUBJECT_ROLE.L018, subjectQuantity: LESSON_SUBJECT_QUANTITY.L018, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.SentenceContext, // NA - T_NO
  L019: { topicIntent: LESSON_TOPIC_INTENT.L019, topicProximity: LESSON_PROXIMITY.L019, topicDestination: LESSON_TOPIC_DESTINATION.L019, eventDirection: LESSON_DIRECTION.L019, eventOccurance: LESSON_EVENT_OCCURANCE.L019, eventDuration: LESSON_EVENT_DURATION.L019, eventPOV: LESSON_POV.L019, subjectConnection: LESSON_SUBJECT_CONNECTION.L019, subjectRole: LESSON_SUBJECT_ROLE.L019, subjectQuantity: LESSON_SUBJECT_QUANTITY.L019, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.SentenceContext, // T - T_ADJ
  L020: { topicIntent: LESSON_TOPIC_INTENT.L020, topicProximity: LESSON_PROXIMITY.L020, topicDestination: LESSON_TOPIC_DESTINATION.L020, eventDirection: LESSON_DIRECTION.L020, eventOccurance: LESSON_EVENT_OCCURANCE.L020, eventDuration: LESSON_EVENT_DURATION.L020, eventPOV: LESSON_POV.L020, subjectConnection: LESSON_SUBJECT_CONNECTION.L020, subjectRole: LESSON_SUBJECT_ROLE.L020, subjectQuantity: LESSON_SUBJECT_QUANTITY.L020, __typename: __TYPENAME_SENTENCE_CONTEXT, } as Util.SentenceContext, // T - T_ADV
  // L021:
  // L022: 
  // L023: 
  // L024: 
  // L025: 
  // L026: 
  // L027: 
};




