import {
  LESSON_TITLE,
  LESSON_DESCRIPTION,
  LESSON_EXPLANATION,
  LESSON_RESOURCES,
} from './lessonConfig';

import {
  LESSON_TOPIC_INTENT,
  LESSON_PROXIMITY,
  LESSON_TOPIC_DESTINATION,
  LESSON_DIRECTION,
  LESSON_EVENT_OCCURANCE,
  LESSON_EVENT_DURATION,
  LESSON_POV,
  LESSON_SUBJECT_CONNECTION,
  LESSON_SUBJECT_ROLE,
  LESSON_SUBJECT_QUANTITY,
} from './contextConfig';

import {
  LESSON_PRE_OPTIONS,
} from './optionsConfig';

import {
  LESSON_PRE_MODIFIERS,
} from './modifiersConfig';

import {
  __TYPENAME_PRE_SENTENCE_CONTEXT,
} from '../constants/typeNameConstants';



export const L001 = {
  LESSON_TITLE: LESSON_TITLE.L001 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L001 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L001 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L001 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L001 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L001 as Util.PreModifiers,
};

export const L002 = {
  LESSON_TITLE: LESSON_TITLE.L002 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L002 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L002 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L002 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L002 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L002 as Util.PreModifiers,
};

export const L003 = {
  LESSON_TITLE: LESSON_TITLE.L003 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L003 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L003 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L003 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L003 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L003 as Util.PreModifiers,
};

export const L004 = {
  LESSON_TITLE: LESSON_TITLE.L004 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L004 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L004 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L004 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L004 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L004 as Util.PreModifiers,
};

export const L005 = {
  LESSON_TITLE: LESSON_TITLE.L005 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L005 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L005 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L005 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L005 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L005 as Util.PreModifiers,
};

export const L006 = {
  LESSON_TITLE: LESSON_TITLE.L006 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L006 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L006 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L006 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L006 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L006 as Util.PreModifiers,
};

export const L007 = {
  LESSON_TITLE: LESSON_TITLE.L007 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L007 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L007 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L007 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L007 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L007 as Util.PreModifiers,
};

export const L008 = {
  LESSON_TITLE: LESSON_TITLE.L008 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L008 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L008 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L008 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L008 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L008 as Util.PreModifiers,
};

export const L009 = {
  LESSON_TITLE: LESSON_TITLE.L009 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L009 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L009 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L009 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L009 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L009 as Util.PreModifiers,
};

export const L010 = {
  LESSON_TITLE: LESSON_TITLE.L010 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L010 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L010 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L010 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L010 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L010 as Util.PreModifiers,
};

export const L011 = {
  LESSON_TITLE: LESSON_TITLE.L011 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L011 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L011 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L011 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L011 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L011 as Util.PreModifiers,
};

export const L012 = {
  LESSON_TITLE: LESSON_TITLE.L012 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L012 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L012 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L012 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L012 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L012 as Util.PreModifiers,
};

export const L013 = {
  LESSON_TITLE: LESSON_TITLE.L013 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L013 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L013 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L013 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L013 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L013 as Util.PreModifiers,
};

export const L014 = {
  LESSON_TITLE: LESSON_TITLE.L014 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L014 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L014 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L014 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L014 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L014 as Util.PreModifiers,
};

export const L015 = {
  LESSON_TITLE: LESSON_TITLE.L015 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L015 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L015 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L015 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L015 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L015 as Util.PreModifiers,
};

export const L016 = {
  LESSON_TITLE: LESSON_TITLE.L016 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L016 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L016 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L016 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L016 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L016 as Util.PreModifiers,
};

export const L017 = {
  LESSON_TITLE: LESSON_TITLE.L017 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L017 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L017 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L017 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L017 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L017 as Util.PreModifiers,
};

export const L018 = {
  LESSON_TITLE: LESSON_TITLE.L018 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L018 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L018 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L018 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L018 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L018 as Util.PreModifiers,
};

export const L019 = {
  LESSON_TITLE: LESSON_TITLE.L019 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L019 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L019 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L019 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L019 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L019 as Util.PreModifiers,
}

export const L020 = {
  LESSON_TITLE: LESSON_TITLE.L020 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L020 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L020 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L020 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L020 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L020 as Util.PreModifiers,
}

export const L021 = {
  LESSON_TITLE: LESSON_TITLE.L021 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L021 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L021 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L021 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L021 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L021 as Util.PreModifiers,
}

export const L022 = {
  LESSON_TITLE: LESSON_TITLE.L022 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L022 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L022 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L022 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L022 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L022 as Util.PreModifiers,
}

export const L023 = {
  LESSON_TITLE: LESSON_TITLE.L023 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L023 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L023 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L023 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L023 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L023 as Util.PreModifiers,
}

export const L024 = {
  LESSON_TITLE: LESSON_TITLE.L024 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L024 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L024 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L024 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L024 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L024 as Util.PreModifiers,
}

export const L025 = {
  LESSON_TITLE: LESSON_TITLE.L025 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L025 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L025 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L025 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L025 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L025 as Util.PreModifiers,
}

export const L026 = {
  LESSON_TITLE: LESSON_TITLE.L026 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L026 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L026 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L026 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L026 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L026 as Util.PreModifiers,
}

export const L027 = {
  LESSON_TITLE: LESSON_TITLE.L027 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L027 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L027 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L027 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L027 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L027 as Util.PreModifiers,
}

export const L028 = {
  LESSON_TITLE: LESSON_TITLE.L028 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L028 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L028 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L028 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L028 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L028 as Util.PreModifiers,
}

export const L029 = {
  LESSON_TITLE: LESSON_TITLE.L029 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L029 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L029 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L029 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L029 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L029 as Util.PreModifiers,
}

export const L030 = {
  LESSON_TITLE: LESSON_TITLE.L030 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L030 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L030 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L030 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L030 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L030 as Util.PreModifiers,
}

export const L031 = {
  LESSON_TITLE: LESSON_TITLE.L031 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L031 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L031 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L031 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L031 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L031 as Util.PreModifiers,
}

export const L032 = {
  LESSON_TITLE: LESSON_TITLE.L032 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L032 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L032 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L032 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L032 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L032 as Util.PreModifiers,
}

export const L033 = {
  LESSON_TITLE: LESSON_TITLE.L033 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L033 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L033 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L033 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L033 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L033 as Util.PreModifiers,
}

export const L034 = {
  LESSON_TITLE: LESSON_TITLE.L034 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L034 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L034 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L034 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L034 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L034 as Util.PreModifiers,
}

export const L035 = {
  LESSON_TITLE: LESSON_TITLE.L035 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L035 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L035 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L035 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L035 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L035 as Util.PreModifiers,
}

export const L036 = {
  LESSON_TITLE: LESSON_TITLE.L036 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L036 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L036 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L036 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L036 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L036 as Util.PreModifiers,
}

export const L037 = {
  LESSON_TITLE: LESSON_TITLE.L037 as string,
  LESSON_DESCRIPTION: LESSON_DESCRIPTION.L037 as string,
  LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L037 as Util.PreOptions,
  LESSON_EXPLANATION: LESSON_EXPLANATION.L037 as string[],
  LESSON_RESOURCES: LESSON_RESOURCES.L037 as Util.Resource[],
  LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L037 as Util.PreModifiers,
}

// export const L038 = {
//   LESSON_TITLE: LESSON_TITLE.L038 as string,
//   LESSON_DESCRIPTION: LESSON_DESCRIPTION.L038 as string,
//   LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L038 as Util.PreOptions,
//   LESSON_EXPLANATION: LESSON_EXPLANATION.L038 as string[],
//   LESSON_RESOURCES: LESSON_RESOURCES.L038 as Util.Resource[],
//   LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L038 as Util.PreModifiers,
// }

// export const L039 = {
//   LESSON_TITLE: LESSON_TITLE.L039 as string,
//   LESSON_DESCRIPTION: LESSON_DESCRIPTION.L039 as string,
//   LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L039 as Util.PreOptions,
//   LESSON_EXPLANATION: LESSON_EXPLANATION.L039 as string[],
//   LESSON_RESOURCES: LESSON_RESOURCES.L039 as Util.Resource[],
//   LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L039 as Util.PreModifiers,
// }

// export const L040 = {
//   LESSON_TITLE: LESSON_TITLE.L040 as string,
//   LESSON_DESCRIPTION: LESSON_DESCRIPTION.L040 as string,
//   LESSON_PRE_OPTIONS: LESSON_PRE_OPTIONS.L040 as Util.PreOptions,
//   LESSON_EXPLANATION: LESSON_EXPLANATION.L040 as string[],
//   LESSON_RESOURCES: LESSON_RESOURCES.L040 as Util.Resource[],
//   LESSON_PRE_MODIFIERS: LESSON_PRE_MODIFIERS.L040 as Util.PreModifiers,
// }

export const LESSON_PRE_SENTENCE_CONTEXT = {
  L001: { topicIntentArray: LESSON_TOPIC_INTENT.L001, topicProximityArray: LESSON_PROXIMITY.L001, topicDestinationArray: LESSON_TOPIC_DESTINATION.L001, eventDirectionArray: LESSON_DIRECTION.L001, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L001, eventDurationArray: LESSON_EVENT_DURATION.L001, eventPOVArray: LESSON_POV.L001, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L001, subjectRoleArray: LESSON_SUBJECT_ROLE.L001, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L001, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext,
  L002: { topicIntentArray: LESSON_TOPIC_INTENT.L002, topicProximityArray: LESSON_PROXIMITY.L002, topicDestinationArray: LESSON_TOPIC_DESTINATION.L002, eventDirectionArray: LESSON_DIRECTION.L002, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L002, eventDurationArray: LESSON_EVENT_DURATION.L002, eventPOVArray: LESSON_POV.L002, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L002, subjectRoleArray: LESSON_SUBJECT_ROLE.L002, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L002, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext,
  L003: { topicIntentArray: LESSON_TOPIC_INTENT.L003, topicProximityArray: LESSON_PROXIMITY.L003, topicDestinationArray: LESSON_TOPIC_DESTINATION.L003, eventDirectionArray: LESSON_DIRECTION.L003, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L003, eventDurationArray: LESSON_EVENT_DURATION.L003, eventPOVArray: LESSON_POV.L003, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L003, subjectRoleArray: LESSON_SUBJECT_ROLE.L003, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L003, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext,
  L004: { topicIntentArray: LESSON_TOPIC_INTENT.L004, topicProximityArray: LESSON_PROXIMITY.L004, topicDestinationArray: LESSON_TOPIC_DESTINATION.L004, eventDirectionArray: LESSON_DIRECTION.L004, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L004, eventDurationArray: LESSON_EVENT_DURATION.L004, eventPOVArray: LESSON_POV.L004, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L004, subjectRoleArray: LESSON_SUBJECT_ROLE.L004, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L004, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext,
  L005: { topicIntentArray: LESSON_TOPIC_INTENT.L005, topicProximityArray: LESSON_PROXIMITY.L005, topicDestinationArray: LESSON_TOPIC_DESTINATION.L005, eventDirectionArray: LESSON_DIRECTION.L005, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L005, eventDurationArray: LESSON_EVENT_DURATION.L005, eventPOVArray: LESSON_POV.L005, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L005, subjectRoleArray: LESSON_SUBJECT_ROLE.L005, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L005, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext,
  L006: { topicIntentArray: LESSON_TOPIC_INTENT.L006, topicProximityArray: LESSON_PROXIMITY.L006, topicDestinationArray: LESSON_TOPIC_DESTINATION.L006, eventDirectionArray: LESSON_DIRECTION.L006, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L006, eventDurationArray: LESSON_EVENT_DURATION.L006, eventPOVArray: LESSON_POV.L006, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L006, subjectRoleArray: LESSON_SUBJECT_ROLE.L006, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L006, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext,
  L007: { topicIntentArray: LESSON_TOPIC_INTENT.L007, topicProximityArray: LESSON_PROXIMITY.L007, topicDestinationArray: LESSON_TOPIC_DESTINATION.L007, eventDirectionArray: LESSON_DIRECTION.L007, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L007, eventDurationArray: LESSON_EVENT_DURATION.L007, eventPOVArray: LESSON_POV.L007, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L007, subjectRoleArray: LESSON_SUBJECT_ROLE.L007, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L007, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext,
  L008: { topicIntentArray: LESSON_TOPIC_INTENT.L008, topicProximityArray: LESSON_PROXIMITY.L008, topicDestinationArray: LESSON_TOPIC_DESTINATION.L008, eventDirectionArray: LESSON_DIRECTION.L008, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L008, eventDurationArray: LESSON_EVENT_DURATION.L008, eventPOVArray: LESSON_POV.L008, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L008, subjectRoleArray: LESSON_SUBJECT_ROLE.L008, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L008, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext,
  L009: { topicIntentArray: LESSON_TOPIC_INTENT.L009, topicProximityArray: LESSON_PROXIMITY.L009, topicDestinationArray: LESSON_TOPIC_DESTINATION.L009, eventDirectionArray: LESSON_DIRECTION.L009, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L009, eventDurationArray: LESSON_EVENT_DURATION.L009, eventPOVArray: LESSON_POV.L009, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L009, subjectRoleArray: LESSON_SUBJECT_ROLE.L009, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L009, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext,
  L010: { topicIntentArray: LESSON_TOPIC_INTENT.L010, topicProximityArray: LESSON_PROXIMITY.L010, topicDestinationArray: LESSON_TOPIC_DESTINATION.L010, eventDirectionArray: LESSON_DIRECTION.L010, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L010, eventDurationArray: LESSON_EVENT_DURATION.L010, eventPOVArray: LESSON_POV.L010, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L010, subjectRoleArray: LESSON_SUBJECT_ROLE.L010, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L010, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext,
  L011: { topicIntentArray: LESSON_TOPIC_INTENT.L011, topicProximityArray: LESSON_PROXIMITY.L011, topicDestinationArray: LESSON_TOPIC_DESTINATION.L011, eventDirectionArray: LESSON_DIRECTION.L011, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L011, eventDurationArray: LESSON_EVENT_DURATION.L011, eventPOVArray: LESSON_POV.L011, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L011, subjectRoleArray: LESSON_SUBJECT_ROLE.L011, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L011, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext,
  L012: { topicIntentArray: LESSON_TOPIC_INTENT.L012, topicProximityArray: LESSON_PROXIMITY.L012, topicDestinationArray: LESSON_TOPIC_DESTINATION.L012, eventDirectionArray: LESSON_DIRECTION.L012, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L012, eventDurationArray: LESSON_EVENT_DURATION.L012, eventPOVArray: LESSON_POV.L012, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L012, subjectRoleArray: LESSON_SUBJECT_ROLE.L012, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L012, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext,
  L013: { topicIntentArray: LESSON_TOPIC_INTENT.L013, topicProximityArray: LESSON_PROXIMITY.L013, topicDestinationArray: LESSON_TOPIC_DESTINATION.L013, eventDirectionArray: LESSON_DIRECTION.L013, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L013, eventDurationArray: LESSON_EVENT_DURATION.L013, eventPOVArray: LESSON_POV.L013, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L013, subjectRoleArray: LESSON_SUBJECT_ROLE.L013, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L013, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext,
  L014: { topicIntentArray: LESSON_TOPIC_INTENT.L014, topicProximityArray: LESSON_PROXIMITY.L014, topicDestinationArray: LESSON_TOPIC_DESTINATION.L014, eventDirectionArray: LESSON_DIRECTION.L014, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L014, eventDurationArray: LESSON_EVENT_DURATION.L014, eventPOVArray: LESSON_POV.L014, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L014, subjectRoleArray: LESSON_SUBJECT_ROLE.L014, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L014, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext,
  L015: { topicIntentArray: LESSON_TOPIC_INTENT.L015, topicProximityArray: LESSON_PROXIMITY.L015, topicDestinationArray: LESSON_TOPIC_DESTINATION.L015, eventDirectionArray: LESSON_DIRECTION.L015, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L015, eventDurationArray: LESSON_EVENT_DURATION.L015, eventPOVArray: LESSON_POV.L015, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L015, subjectRoleArray: LESSON_SUBJECT_ROLE.L015, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L015, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext,
  L016: { topicIntentArray: LESSON_TOPIC_INTENT.L016, topicProximityArray: LESSON_PROXIMITY.L016, topicDestinationArray: LESSON_TOPIC_DESTINATION.L016, eventDirectionArray: LESSON_DIRECTION.L016, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L016, eventDurationArray: LESSON_EVENT_DURATION.L016, eventPOVArray: LESSON_POV.L016, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L016, subjectRoleArray: LESSON_SUBJECT_ROLE.L016, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L016, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext,
  L017: { topicIntentArray: LESSON_TOPIC_INTENT.L017, topicProximityArray: LESSON_PROXIMITY.L017, topicDestinationArray: LESSON_TOPIC_DESTINATION.L017, eventDirectionArray: LESSON_DIRECTION.L017, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L017, eventDurationArray: LESSON_EVENT_DURATION.L017, eventPOVArray: LESSON_POV.L017, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L017, subjectRoleArray: LESSON_SUBJECT_ROLE.L017, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L017, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext,
  L018: { topicIntentArray: LESSON_TOPIC_INTENT.L018, topicProximityArray: LESSON_PROXIMITY.L018, topicDestinationArray: LESSON_TOPIC_DESTINATION.L018, eventDirectionArray: LESSON_DIRECTION.L018, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L018, eventDurationArray: LESSON_EVENT_DURATION.L018, eventPOVArray: LESSON_POV.L018, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L018, subjectRoleArray: LESSON_SUBJECT_ROLE.L018, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L018, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext,
  L019: { topicIntentArray: LESSON_TOPIC_INTENT.L019, topicProximityArray: LESSON_PROXIMITY.L019, topicDestinationArray: LESSON_TOPIC_DESTINATION.L019, eventDirectionArray: LESSON_DIRECTION.L019, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L019, eventDurationArray: LESSON_EVENT_DURATION.L019, eventPOVArray: LESSON_POV.L019, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L019, subjectRoleArray: LESSON_SUBJECT_ROLE.L019, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L019, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext,
  L020: { topicIntentArray: LESSON_TOPIC_INTENT.L020, topicProximityArray: LESSON_PROXIMITY.L020, topicDestinationArray: LESSON_TOPIC_DESTINATION.L020, eventDirectionArray: LESSON_DIRECTION.L020, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L020, eventDurationArray: LESSON_EVENT_DURATION.L020, eventPOVArray: LESSON_POV.L020, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L020, subjectRoleArray: LESSON_SUBJECT_ROLE.L020, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L020, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext,
  L021: { topicIntentArray: LESSON_TOPIC_INTENT.L021, topicProximityArray: LESSON_PROXIMITY.L021, topicDestinationArray: LESSON_TOPIC_DESTINATION.L021, eventDirectionArray: LESSON_DIRECTION.L021, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L021, eventDurationArray: LESSON_EVENT_DURATION.L021, eventPOVArray: LESSON_POV.L021, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L021, subjectRoleArray: LESSON_SUBJECT_ROLE.L021, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L021, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext, 
  L022: { topicIntentArray: LESSON_TOPIC_INTENT.L022, topicProximityArray: LESSON_PROXIMITY.L022, topicDestinationArray: LESSON_TOPIC_DESTINATION.L022, eventDirectionArray: LESSON_DIRECTION.L022, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L022, eventDurationArray: LESSON_EVENT_DURATION.L022, eventPOVArray: LESSON_POV.L022, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L022, subjectRoleArray: LESSON_SUBJECT_ROLE.L022, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L022, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext, 
  L023: { topicIntentArray: LESSON_TOPIC_INTENT.L023, topicProximityArray: LESSON_PROXIMITY.L023, topicDestinationArray: LESSON_TOPIC_DESTINATION.L023, eventDirectionArray: LESSON_DIRECTION.L023, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L023, eventDurationArray: LESSON_EVENT_DURATION.L023, eventPOVArray: LESSON_POV.L023, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L023, subjectRoleArray: LESSON_SUBJECT_ROLE.L023, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L023, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext, 
  L024: { topicIntentArray: LESSON_TOPIC_INTENT.L024, topicProximityArray: LESSON_PROXIMITY.L024, topicDestinationArray: LESSON_TOPIC_DESTINATION.L024, eventDirectionArray: LESSON_DIRECTION.L024, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L024, eventDurationArray: LESSON_EVENT_DURATION.L024, eventPOVArray: LESSON_POV.L024, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L024, subjectRoleArray: LESSON_SUBJECT_ROLE.L024, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L024, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext, 
  L025: { topicIntentArray: LESSON_TOPIC_INTENT.L025, topicProximityArray: LESSON_PROXIMITY.L025, topicDestinationArray: LESSON_TOPIC_DESTINATION.L025, eventDirectionArray: LESSON_DIRECTION.L025, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L025, eventDurationArray: LESSON_EVENT_DURATION.L025, eventPOVArray: LESSON_POV.L025, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L025, subjectRoleArray: LESSON_SUBJECT_ROLE.L025, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L025, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext, 
  L026: { topicIntentArray: LESSON_TOPIC_INTENT.L026, topicProximityArray: LESSON_PROXIMITY.L026, topicDestinationArray: LESSON_TOPIC_DESTINATION.L026, eventDirectionArray: LESSON_DIRECTION.L026, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L026, eventDurationArray: LESSON_EVENT_DURATION.L026, eventPOVArray: LESSON_POV.L026, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L026, subjectRoleArray: LESSON_SUBJECT_ROLE.L026, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L026, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext, 
  L027: { topicIntentArray: LESSON_TOPIC_INTENT.L027, topicProximityArray: LESSON_PROXIMITY.L027, topicDestinationArray: LESSON_TOPIC_DESTINATION.L027, eventDirectionArray: LESSON_DIRECTION.L027, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L027, eventDurationArray: LESSON_EVENT_DURATION.L027, eventPOVArray: LESSON_POV.L027, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L027, subjectRoleArray: LESSON_SUBJECT_ROLE.L027, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L027, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext, 
  L028: { topicIntentArray: LESSON_TOPIC_INTENT.L028, topicProximityArray: LESSON_PROXIMITY.L028, topicDestinationArray: LESSON_TOPIC_DESTINATION.L028, eventDirectionArray: LESSON_DIRECTION.L028, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L028, eventDurationArray: LESSON_EVENT_DURATION.L028, eventPOVArray: LESSON_POV.L028, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L028, subjectRoleArray: LESSON_SUBJECT_ROLE.L028, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L028, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext, 
  L029: { topicIntentArray: LESSON_TOPIC_INTENT.L029, topicProximityArray: LESSON_PROXIMITY.L029, topicDestinationArray: LESSON_TOPIC_DESTINATION.L029, eventDirectionArray: LESSON_DIRECTION.L029, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L029, eventDurationArray: LESSON_EVENT_DURATION.L029, eventPOVArray: LESSON_POV.L029, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L029, subjectRoleArray: LESSON_SUBJECT_ROLE.L029, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L029, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext, 
  L030: { topicIntentArray: LESSON_TOPIC_INTENT.L030, topicProximityArray: LESSON_PROXIMITY.L030, topicDestinationArray: LESSON_TOPIC_DESTINATION.L030, eventDirectionArray: LESSON_DIRECTION.L030, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L030, eventDurationArray: LESSON_EVENT_DURATION.L030, eventPOVArray: LESSON_POV.L030, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L030, subjectRoleArray: LESSON_SUBJECT_ROLE.L030, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L030, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext, 
  L031: { topicIntentArray: LESSON_TOPIC_INTENT.L031, topicProximityArray: LESSON_PROXIMITY.L031, topicDestinationArray: LESSON_TOPIC_DESTINATION.L031, eventDirectionArray: LESSON_DIRECTION.L031, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L031, eventDurationArray: LESSON_EVENT_DURATION.L031, eventPOVArray: LESSON_POV.L031, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L031, subjectRoleArray: LESSON_SUBJECT_ROLE.L031, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L031, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext, 
  L032: { topicIntentArray: LESSON_TOPIC_INTENT.L032, topicProximityArray: LESSON_PROXIMITY.L032, topicDestinationArray: LESSON_TOPIC_DESTINATION.L032, eventDirectionArray: LESSON_DIRECTION.L032, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L032, eventDurationArray: LESSON_EVENT_DURATION.L032, eventPOVArray: LESSON_POV.L032, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L032, subjectRoleArray: LESSON_SUBJECT_ROLE.L032, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L032, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext, 
  L033: { topicIntentArray: LESSON_TOPIC_INTENT.L033, topicProximityArray: LESSON_PROXIMITY.L033, topicDestinationArray: LESSON_TOPIC_DESTINATION.L033, eventDirectionArray: LESSON_DIRECTION.L033, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L033, eventDurationArray: LESSON_EVENT_DURATION.L033, eventPOVArray: LESSON_POV.L033, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L033, subjectRoleArray: LESSON_SUBJECT_ROLE.L033, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L033, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext, 
  L034: { topicIntentArray: LESSON_TOPIC_INTENT.L034, topicProximityArray: LESSON_PROXIMITY.L034, topicDestinationArray: LESSON_TOPIC_DESTINATION.L034, eventDirectionArray: LESSON_DIRECTION.L034, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L034, eventDurationArray: LESSON_EVENT_DURATION.L034, eventPOVArray: LESSON_POV.L034, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L034, subjectRoleArray: LESSON_SUBJECT_ROLE.L034, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L034, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext, 
  L035: { topicIntentArray: LESSON_TOPIC_INTENT.L035, topicProximityArray: LESSON_PROXIMITY.L035, topicDestinationArray: LESSON_TOPIC_DESTINATION.L035, eventDirectionArray: LESSON_DIRECTION.L035, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L035, eventDurationArray: LESSON_EVENT_DURATION.L035, eventPOVArray: LESSON_POV.L035, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L035, subjectRoleArray: LESSON_SUBJECT_ROLE.L035, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L035, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext, 
  L036: { topicIntentArray: LESSON_TOPIC_INTENT.L036, topicProximityArray: LESSON_PROXIMITY.L036, topicDestinationArray: LESSON_TOPIC_DESTINATION.L036, eventDirectionArray: LESSON_DIRECTION.L036, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L036, eventDurationArray: LESSON_EVENT_DURATION.L036, eventPOVArray: LESSON_POV.L036, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L036, subjectRoleArray: LESSON_SUBJECT_ROLE.L036, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L036, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext, 
  L037: { topicIntentArray: LESSON_TOPIC_INTENT.L037, topicProximityArray: LESSON_PROXIMITY.L037, topicDestinationArray: LESSON_TOPIC_DESTINATION.L037, eventDirectionArray: LESSON_DIRECTION.L037, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L037, eventDurationArray: LESSON_EVENT_DURATION.L037, eventPOVArray: LESSON_POV.L037, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L037, subjectRoleArray: LESSON_SUBJECT_ROLE.L037, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L037, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext, 
  L038: { topicIntentArray: LESSON_TOPIC_INTENT.L038, topicProximityArray: LESSON_PROXIMITY.L038, topicDestinationArray: LESSON_TOPIC_DESTINATION.L038, eventDirectionArray: LESSON_DIRECTION.L038, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L038, eventDurationArray: LESSON_EVENT_DURATION.L038, eventPOVArray: LESSON_POV.L038, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L038, subjectRoleArray: LESSON_SUBJECT_ROLE.L038, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L038, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext, 
  // L039: { topicIntextArray: LESSON_TOPIC_INTENT.L039, topicProximityArray: LESSON_PROXIMITY.L039, topicDestinationArray: LESSON_TOPIC_DESTINATION.L039, eventDirectionArray: LESSON_DIRECTION.L039, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L039, eventDurationArray: LESSON_EVENT_DURATION.L039, eventPOVArray: LESSON_POV.L039, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L039, subjectRoleArray: LESSON_SUBJECT_ROLE.L039, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L039, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext,
  // L040: { topicIntextArray: LESSON_TOPIC_INTENT.L040, topicProximityArray: LESSON_PROXIMITY.L040, topicDestinationArray: LESSON_TOPIC_DESTINATION.L040, eventDirectionArray: LESSON_DIRECTION.L040, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L040, eventDurationArray: LESSON_EVENT_DURATION.L040, eventPOVArray: LESSON_POV.L040, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L040, subjectRoleArray: LESSON_SUBJECT_ROLE.L040, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L040, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext,
  // L041: { topicIntextArray: LESSON_TOPIC_INTENT.L041, topicProximityArray: LESSON_PROXIMITY.L041, topicDestinationArray: LESSON_TOPIC_DESTINATION.L041, eventDirectionArray: LESSON_DIRECTION.L041, eventOccuranceArray: LESSON_EVENT_OCCURANCE.L041, eventDurationArray: LESSON_EVENT_DURATION.L041, eventPOVArray: LESSON_POV.L041, subjectConnectionArray: LESSON_SUBJECT_CONNECTION.L041, subjectRoleArray: LESSON_SUBJECT_ROLE.L041, subjectQuantityArray: LESSON_SUBJECT_QUANTITY.L041, __typename: __TYPENAME_PRE_SENTENCE_CONTEXT, } as Util.PreSentenceContext,

};




