import {
  __TYPENAME_SENTENCE_CONTEXT,
} from '../constants/typeNameConstants';


import {
  CONTEXT_INTENT_EXISTENCE,
  // CONTEXT_INTENT_POSSESSION,
  CONTEXT_INTENT_ACTION,
} from '../constants/contextConstants';

export const LESSON_TOPIC_INTENT = {
  L001: [CONTEXT_INTENT_EXISTENCE], // T
  L002: [CONTEXT_INTENT_EXISTENCE], // WA_TS, MO_TS
  L003: [CONTEXT_INTENT_EXISTENCE], // GA_TS
  L004: [CONTEXT_INTENT_EXISTENCE], // WA_TS, GA_TS
  L005: [CONTEXT_INTENT_EXISTENCE], // WA_TS, MO_TS, GA_TS
  L006: [CONTEXT_INTENT_ACTION],    // V
  L007: [CONTEXT_INTENT_ACTION],    // V
  L008: [CONTEXT_INTENT_ACTION],    // V
  L009: [CONTEXT_INTENT_ACTION],    // WO_SV
  L010: [CONTEXT_INTENT_ACTION],    // NI_SV
  L011: [CONTEXT_INTENT_ACTION],    // DE_SV
  L012: [CONTEXT_INTENT_ACTION],    // WO_SV, NI_SV
  L013: [CONTEXT_INTENT_ACTION],    // NI_SV, DE_SV
  L014: [CONTEXT_INTENT_ACTION],    // DE_SV, WO_SV
  L015: [CONTEXT_INTENT_ACTION],    // WO_SV, NI_SV, DE_SV
  L016: [''],                       // KARA_SV
  L017: [''],                       // MADE_SV
  L018: [''],                       // NA - T_NO
  L019: [''],                       // T - T_ADJ
  L020: [''],                       // T - T_ADV
  // L021:
  // L022: 
  // L023: 
  // L024: 
  // L025: 
  // L026: 
  // L027: 
};

import {

  // CONTEXT_PROXIMITY_RANDOM,
  // CONTEXT_PROXIMITY_ALONE,
  CONTEXT_PROXIMITY_NEAR,
  // CONTEXT_PROXIMITY_FAR,
  // CONTEXT_PROXIMITY_AT,
  // CONTEXT_PROXIMITY_INSIDE,
} from '../constants/contextConstants';

export const LESSON_PROXIMITY = {
  L001: [CONTEXT_PROXIMITY_NEAR], // T
  L002: [CONTEXT_PROXIMITY_NEAR], // WA_TS, MO_TS
  L003: [CONTEXT_PROXIMITY_NEAR], // GA_TS
  L004: [CONTEXT_PROXIMITY_NEAR], // WA_TS, GA_TS
  L005: [CONTEXT_PROXIMITY_NEAR], // WA_TS, MO_TS, GA_TS
  L006: [CONTEXT_PROXIMITY_NEAR], // V
  L007: [CONTEXT_PROXIMITY_NEAR], // V
  L008: [CONTEXT_PROXIMITY_NEAR], // V
  L009: [CONTEXT_PROXIMITY_NEAR], // WO_SV
  L010: [CONTEXT_PROXIMITY_NEAR], // NI_SV
  L011: [CONTEXT_PROXIMITY_NEAR], // DE_SV
  L012: [CONTEXT_PROXIMITY_NEAR], // WO_SV, NI_SV
  L013: [CONTEXT_PROXIMITY_NEAR], // NI_SV, DE_SV
  L014: [CONTEXT_PROXIMITY_NEAR], // DE_SV, WO_SV
  L015: [CONTEXT_PROXIMITY_NEAR], // WO_SV, NI_SV, DE_SV
  L016: [CONTEXT_PROXIMITY_NEAR], // KARA_SV
  L017: [CONTEXT_PROXIMITY_NEAR], // MADE_SV
  L018: [CONTEXT_PROXIMITY_NEAR], // NA - T_NO
  L019: [CONTEXT_PROXIMITY_NEAR], // T - T_ADJ
  L020: [CONTEXT_PROXIMITY_NEAR], // T - T_ADV
  // L021:
  // L022: 
  // L023: 
  // L024: 
  // L025: 
  // L026: 
  // L027: 
};

import {
  // CONTEXT_TOPIC_DESTINATION_RANDOM,
  CONTEXT_TOPIC_DESTINATION_IRRELEVANT,
  CONTEXT_TOPIC_DESTINATION_NONE,
  // CONTEXT_Y_TOPIC_DESTINATION_ABOVE,
  // CONTEXT_Y_TOPIC_DESTINATION_BELOW,
  // CONTEXT_Y_TOPIC_DESTINATION_BEHIND,
  // CONTEXT_Y_TOPIC_DESTINATION_IN_FRONT,
  // CONTEXT_TOPIC_DESTINATION_ALONG,
  // CONTEXT_TOPIC_DESTINATION_BESIDE,
  // CONTEXT_TOPIC_DESTINATION_WITH,
  // CONTEXT_TOPIC_DESTINATION_BETWEEN,
  // CONTEXT_TOPIC_DESTINATION_THROUGH,
  // CONTEXT_TOPIC_DESTINATION_INSIDE,
  // CONTEXT_TOPIC_DESTINATION_OUTSIDE,
} from '../constants/contextConstants';

export const LESSON_TOPIC_DESTINATION = {
  L001: [CONTEXT_TOPIC_DESTINATION_NONE],       // T
  L002: [CONTEXT_TOPIC_DESTINATION_NONE],       // WA_TS, MO_TS
  L003: [CONTEXT_TOPIC_DESTINATION_NONE],       // GA_TS
  L004: [CONTEXT_TOPIC_DESTINATION_NONE],       // WA_TS, GA_TS
  L005: [CONTEXT_TOPIC_DESTINATION_NONE],       // WA_TS, MO_TS, GA_TS
  L006: [CONTEXT_TOPIC_DESTINATION_NONE],       // V
  L007: [CONTEXT_TOPIC_DESTINATION_NONE],       // V
  L008: [CONTEXT_TOPIC_DESTINATION_NONE],       // V
  L009: [CONTEXT_TOPIC_DESTINATION_IRRELEVANT], // WO_SV
  L010: [CONTEXT_TOPIC_DESTINATION_IRRELEVANT], // NI_SV
  L011: [CONTEXT_TOPIC_DESTINATION_IRRELEVANT], // DE_SV
  L012: [CONTEXT_TOPIC_DESTINATION_IRRELEVANT], // WO_SV, NI_SV
  L013: [CONTEXT_TOPIC_DESTINATION_IRRELEVANT], // NI_SV, DE_SV
  L014: [CONTEXT_TOPIC_DESTINATION_IRRELEVANT], // DE_SV, WO_SV
  L015: [CONTEXT_TOPIC_DESTINATION_IRRELEVANT], // WO_SV, NI_SV, DE_SV
  L016: [CONTEXT_TOPIC_DESTINATION_NONE],       // KARA_SV
  L017: [CONTEXT_TOPIC_DESTINATION_NONE],       // MADE_SV
  L018: [CONTEXT_TOPIC_DESTINATION_NONE],       // NA - T_NO
  L019: [CONTEXT_TOPIC_DESTINATION_NONE],       // T - T_ADJ
  L020: [CONTEXT_TOPIC_DESTINATION_NONE],       // T - T_ADV
};

import {
  // CONTEXT_DIRECTION_RANDOM,
  CONTEXT_DIRECTION_NONE,
  CONTEXT_DIRECTION_TOWARD,
  // CONTEXT_DIRECTION_AWAY,
  // CONTEXT_Y_DIRECTION_UP,
  // CONTEXT_Y_DIRECTION_DOWN,
  // CONTEXT_X_DIRECTION_LEFT,
  // CONTEXT_X_DIRECTION_RIGHT,
  // CONTEXT_X_DIRECTION_ACROSS,
} from '../constants/contextConstants';

export const LESSON_DIRECTION = {
  L001: [CONTEXT_DIRECTION_NONE],   // T
  L002: [CONTEXT_DIRECTION_NONE],   // WA_TS, MO_TS
  L003: [CONTEXT_DIRECTION_NONE],   // GA_TS
  L004: [CONTEXT_DIRECTION_NONE],   // WA_TS, GA_TS
  L005: [CONTEXT_DIRECTION_NONE],   // WA_TS, MO_TS, GA_TS
  L006: [CONTEXT_DIRECTION_NONE],   // V
  L007: [CONTEXT_DIRECTION_NONE],   // V
  L008: [CONTEXT_DIRECTION_NONE],   // V
  L009: [CONTEXT_DIRECTION_TOWARD], // WO_SV
  L010: [CONTEXT_DIRECTION_TOWARD], // NI_SV
  L011: [CONTEXT_DIRECTION_TOWARD], // DE_SV
  L012: [CONTEXT_DIRECTION_TOWARD], // WO_SV, NI_SV
  L013: [CONTEXT_DIRECTION_TOWARD], // NI_SV, DE_SV
  L014: [CONTEXT_DIRECTION_TOWARD], // DE_SV, WO_SV
  L015: [CONTEXT_DIRECTION_TOWARD], // WO_SV, NI_SV, DE_SV
  L016: [CONTEXT_DIRECTION_NONE],   // KARA_SV
  L017: [CONTEXT_DIRECTION_NONE],   // MADE_SV
  L018: [CONTEXT_DIRECTION_NONE],   // NA - T_NO
  L019: [CONTEXT_DIRECTION_NONE],   // T - T_ADJ
  L020: [CONTEXT_DIRECTION_NONE],   // T - T_ADV
}

import {
  // CONTEXT_EVENT_OCCURANCE_RANDOM,
  // CONTEXT_EVENT_OCCURANCE_BEFORE_PAST,
  CONTEXT_EVENT_OCCURANCE_PAST,
  // CONTEXT_EVENT_OCCURANCE_PAST_NOW,
  // CONTEXT_EVENT_OCCURANCE_PAST_FUTUREPAST,
  CONTEXT_EVENT_OCCURANCE_NOW,
  // CONTEXT_EVENT_OCCURANCE_NOW_FUTURE,
  // CONTEXT_EVENT_OCCURANCE_FUTURE,
} from '../constants/contextConstants';

export const LESSON_EVENT_OCCURANCE = {
  L001: [ CONTEXT_EVENT_OCCURANCE_PAST, CONTEXT_EVENT_OCCURANCE_NOW ], // T
  L002: [ CONTEXT_EVENT_OCCURANCE_PAST, CONTEXT_EVENT_OCCURANCE_NOW ], // WA_TS, MO_TS
  L003: [ CONTEXT_EVENT_OCCURANCE_PAST, CONTEXT_EVENT_OCCURANCE_NOW ], // GA_TS
  L004: [ CONTEXT_EVENT_OCCURANCE_PAST, CONTEXT_EVENT_OCCURANCE_NOW ], // WA_TS, GA_TS
  L005: [ CONTEXT_EVENT_OCCURANCE_PAST, CONTEXT_EVENT_OCCURANCE_NOW ], // WA_TS, MO_TS, GA_TS
  L006: [ CONTEXT_EVENT_OCCURANCE_PAST, CONTEXT_EVENT_OCCURANCE_NOW ], // V
  L007: [ CONTEXT_EVENT_OCCURANCE_PAST, CONTEXT_EVENT_OCCURANCE_NOW ], // V
  L008: [ CONTEXT_EVENT_OCCURANCE_PAST, CONTEXT_EVENT_OCCURANCE_NOW ], // V
  L009: [ CONTEXT_EVENT_OCCURANCE_PAST, CONTEXT_EVENT_OCCURANCE_NOW ], // WO_SV
  L010: [ CONTEXT_EVENT_OCCURANCE_PAST, CONTEXT_EVENT_OCCURANCE_NOW ], // NI_SV
  L011: [ CONTEXT_EVENT_OCCURANCE_PAST, CONTEXT_EVENT_OCCURANCE_NOW ], // DE_SV
  L012: [ CONTEXT_EVENT_OCCURANCE_PAST, CONTEXT_EVENT_OCCURANCE_NOW ], // WO_SV, NI_SV
  L013: [ CONTEXT_EVENT_OCCURANCE_PAST, CONTEXT_EVENT_OCCURANCE_NOW ], // NI_SV, DE_SV
  L014: [ CONTEXT_EVENT_OCCURANCE_PAST, CONTEXT_EVENT_OCCURANCE_NOW ], // DE_SV, WO_SV
  L015: [ CONTEXT_EVENT_OCCURANCE_PAST, CONTEXT_EVENT_OCCURANCE_NOW ], // WO_SV, NI_SV, DE_SV
  L016: [ CONTEXT_EVENT_OCCURANCE_PAST, CONTEXT_EVENT_OCCURANCE_NOW ], // KARA_SV
  L017: [ CONTEXT_EVENT_OCCURANCE_PAST, CONTEXT_EVENT_OCCURANCE_NOW ], // MADE_SV
  L018: [ CONTEXT_EVENT_OCCURANCE_PAST, CONTEXT_EVENT_OCCURANCE_NOW ], // NA - T_NO
  L019: [ CONTEXT_EVENT_OCCURANCE_PAST, CONTEXT_EVENT_OCCURANCE_NOW ], // T - T_ADJ
  L020: [ CONTEXT_EVENT_OCCURANCE_PAST, CONTEXT_EVENT_OCCURANCE_NOW ], // T - T_ADV
};

import {
  // CONTEXT_EVENT_DURATION_RANDOM,
  // CONTEXT_EVENT_DURATION_PARTIAL_CONTINUOUS,
  CONTEXT_EVENT_DURATION_COMPLETE, 
} from '../constants/contextConstants';


export const LESSON_EVENT_DURATION = {
  L001: [CONTEXT_EVENT_DURATION_COMPLETE], // T
  L002: [CONTEXT_EVENT_DURATION_COMPLETE], // WA_TS, MO_TS
  L003: [CONTEXT_EVENT_DURATION_COMPLETE], // GA_TS
  L004: [CONTEXT_EVENT_DURATION_COMPLETE], // WA_TS, GA_TS
  L005: [CONTEXT_EVENT_DURATION_COMPLETE], // WA_TS, MO_TS, GA_TS
  L006: [CONTEXT_EVENT_DURATION_COMPLETE], // V
  L007: [CONTEXT_EVENT_DURATION_COMPLETE], // V
  L008: [CONTEXT_EVENT_DURATION_COMPLETE], // V
  L009: [CONTEXT_EVENT_DURATION_COMPLETE], // WO_SV
  L010: [CONTEXT_EVENT_DURATION_COMPLETE], // NI_SV
  L011: [CONTEXT_EVENT_DURATION_COMPLETE], // DE_SV
  L012: [CONTEXT_EVENT_DURATION_COMPLETE], // WO_SV, NI_SV
  L013: [CONTEXT_EVENT_DURATION_COMPLETE], // NI_SV, DE_SV
  L014: [CONTEXT_EVENT_DURATION_COMPLETE], // DE_SV, WO_SV
  L015: [CONTEXT_EVENT_DURATION_COMPLETE], // WO_SV, NI_SV, DE_SV
  L016: [CONTEXT_EVENT_DURATION_COMPLETE], // KARA_SV
  L017: [CONTEXT_EVENT_DURATION_COMPLETE], // MADE_SV
  L018: [CONTEXT_EVENT_DURATION_COMPLETE], // NA - T_NO
  L019: [CONTEXT_EVENT_DURATION_COMPLETE], // T - T_ADJ
  L020: [CONTEXT_EVENT_DURATION_COMPLETE], // T - T_ADV
}

import {
  // CONTEXT_POV_RANDOM,
  CONTEXT_POV_SELF_SINGULAR,
  // CONTEXT_POV_YOU_SINGULAR,
  CONTEXT_POV_HESHEIT_SINGULAR,
  // CONTEXT_POV_WE_PLURAL,
  // CONTEXT_POV_YOU_PLURAL,
  // CONTEXT_POV_THEYTHOSE_PLURAL,
} from '../constants/contextConstants';

export const LESSON_POV = {
  L001: [CONTEXT_POV_HESHEIT_SINGULAR], // T
  L002: [CONTEXT_POV_HESHEIT_SINGULAR], // WA_TS, MO_TS
  L003: [CONTEXT_POV_HESHEIT_SINGULAR], // GA_TS
  L004: [CONTEXT_POV_HESHEIT_SINGULAR], // WA_TS, GA_TS
  L005: [CONTEXT_POV_HESHEIT_SINGULAR], // WA_TS, MO_TS, GA_TS
  L006: [CONTEXT_POV_SELF_SINGULAR], // V
  L007: [CONTEXT_POV_SELF_SINGULAR], // V
  L008: [CONTEXT_POV_SELF_SINGULAR], // V
  L009: [CONTEXT_POV_SELF_SINGULAR], // WO_SV
  L010: [CONTEXT_POV_SELF_SINGULAR], // NI_SV
  L011: [CONTEXT_POV_SELF_SINGULAR], // DE_SV
  L012: [CONTEXT_POV_SELF_SINGULAR], // WO_SV, NI_SV
  L013: [CONTEXT_POV_SELF_SINGULAR], // NI_SV, DE_SV
  L014: [CONTEXT_POV_SELF_SINGULAR], // DE_SV, WO_SV
  L015: [CONTEXT_POV_SELF_SINGULAR], // WO_SV, NI_SV, DE_SV
  L016: [CONTEXT_POV_SELF_SINGULAR], // KARA_SV
  L017: [CONTEXT_POV_SELF_SINGULAR], // MADE_SV
  L018: [CONTEXT_POV_SELF_SINGULAR], // NA - T_NO
  L019: [CONTEXT_POV_SELF_SINGULAR], // T - T_ADJ
  L020: [CONTEXT_POV_SELF_SINGULAR], // T - T_ADV
};

import {
  // CONTEXT_SUBJECT_CONNECTION_RANDOM,
  // CONTEXT_SUBJECT_CONNECTION_IN_CONJUNCTION,
  CONTEXT_SUBJECT_CONNECTION_INDEPENDENT,
} from '../constants/contextConstants';

export const LESSON_SUBJECT_CONNECTION = {
  L001: [CONTEXT_SUBJECT_CONNECTION_INDEPENDENT], // T
  L002: [CONTEXT_SUBJECT_CONNECTION_INDEPENDENT], // WA_TS, MO_TS
  L003: [CONTEXT_SUBJECT_CONNECTION_INDEPENDENT], // GA_TS
  L004: [CONTEXT_SUBJECT_CONNECTION_INDEPENDENT], // WA_TS, GA_TS
  L005: [CONTEXT_SUBJECT_CONNECTION_INDEPENDENT], // WA_TS, MO_TS, GA_TS
  L006: [CONTEXT_SUBJECT_CONNECTION_INDEPENDENT], // V
  L007: [CONTEXT_SUBJECT_CONNECTION_INDEPENDENT], // V
  L008: [CONTEXT_SUBJECT_CONNECTION_INDEPENDENT], // V
  L009: [CONTEXT_SUBJECT_CONNECTION_INDEPENDENT], // WO_SV
  L010: [CONTEXT_SUBJECT_CONNECTION_INDEPENDENT], // NI_SV
  L011: [CONTEXT_SUBJECT_CONNECTION_INDEPENDENT], // DE_SV
  L012: [CONTEXT_SUBJECT_CONNECTION_INDEPENDENT], // WO_SV, NI_SV
  L013: [CONTEXT_SUBJECT_CONNECTION_INDEPENDENT], // NI_SV, DE_SV
  L014: [CONTEXT_SUBJECT_CONNECTION_INDEPENDENT], // DE_SV, WO_SV
  L015: [CONTEXT_SUBJECT_CONNECTION_INDEPENDENT], // WO_SV, NI_SV, DE_SV
  L016: [CONTEXT_SUBJECT_CONNECTION_INDEPENDENT], // KARA_SV
  L017: [CONTEXT_SUBJECT_CONNECTION_INDEPENDENT], // MADE_SV
  L018: [CONTEXT_SUBJECT_CONNECTION_INDEPENDENT], // NA - T_NO
  L019: [CONTEXT_SUBJECT_CONNECTION_INDEPENDENT], // T - T_ADJ
  L020: [CONTEXT_SUBJECT_CONNECTION_INDEPENDENT], // T - T_ADV
};

import {
  // CONTEXT_SUBJECT_ROLE_RANDOM,
  CONTEXT_SUBJECT_ROLE_DIRECT,
  // CONTEXT_SUBJECT_ROLE_SECOND_HAND,
  // CONTEXT_SUBJECT_ROLE_ON_BEHALF_OF,
  // CONTEXT_SUBJECT_ROLE_BECAUSE_OF,
} from '../constants/contextConstants';

export const LESSON_SUBJECT_ROLE = {
  L001: [CONTEXT_SUBJECT_ROLE_DIRECT], // T
  L002: [CONTEXT_SUBJECT_ROLE_DIRECT], // WA_TS, MO_TS
  L003: [CONTEXT_SUBJECT_ROLE_DIRECT], // GA_TS
  L004: [CONTEXT_SUBJECT_ROLE_DIRECT], // WA_TS, GA_TS
  L005: [CONTEXT_SUBJECT_ROLE_DIRECT], // WA_TS, MO_TS, GA_TS
  L006: [CONTEXT_SUBJECT_ROLE_DIRECT], // V
  L007: [CONTEXT_SUBJECT_ROLE_DIRECT], // V
  L008: [CONTEXT_SUBJECT_ROLE_DIRECT], // V
  L009: [CONTEXT_SUBJECT_ROLE_DIRECT], // WO_SV
  L010: [CONTEXT_SUBJECT_ROLE_DIRECT], // NI_SV
  L011: [CONTEXT_SUBJECT_ROLE_DIRECT], // DE_SV
  L012: [CONTEXT_SUBJECT_ROLE_DIRECT], // WO_SV, NI_SV
  L013: [CONTEXT_SUBJECT_ROLE_DIRECT], // NI_SV, DE_SV
  L014: [CONTEXT_SUBJECT_ROLE_DIRECT], // DE_SV, WO_SV
  L015: [CONTEXT_SUBJECT_ROLE_DIRECT], // WO_SV, NI_SV, DE_SV
  L016: [CONTEXT_SUBJECT_ROLE_DIRECT], // KARA_SV
  L017: [CONTEXT_SUBJECT_ROLE_DIRECT], // MADE_SV
  L018: [CONTEXT_SUBJECT_ROLE_DIRECT], // NA - T_NO
  L019: [CONTEXT_SUBJECT_ROLE_DIRECT], // T - T_ADJ
  L020: [CONTEXT_SUBJECT_ROLE_DIRECT], // T - T_ADV
}

import {
  // CONTEXT_SUBJECT_QUANTITY_RANDOM,
  CONTEXT_SUBJECT_QUANTITY_SINGLE,
  // CONTEXT_SUBJECT_QUANTITY_MULTIPLE,
} from '../constants/contextConstants';

export const LESSON_SUBJECT_QUANTITY = {
  L001: [CONTEXT_SUBJECT_QUANTITY_SINGLE], // T
  L002: [CONTEXT_SUBJECT_QUANTITY_SINGLE], // WA_TS, MO_TS
  L003: [CONTEXT_SUBJECT_QUANTITY_SINGLE], // GA_TS
  L004: [CONTEXT_SUBJECT_QUANTITY_SINGLE], // WA_TS, GA_TS
  L005: [CONTEXT_SUBJECT_QUANTITY_SINGLE], // WA_TS, MO_TS, GA_TS
  L006: [CONTEXT_SUBJECT_QUANTITY_SINGLE], // V
  L007: [CONTEXT_SUBJECT_QUANTITY_SINGLE], // V
  L008: [CONTEXT_SUBJECT_QUANTITY_SINGLE], // V
  L009: [CONTEXT_SUBJECT_QUANTITY_SINGLE], // WO_SV
  L010: [CONTEXT_SUBJECT_QUANTITY_SINGLE], // NI_SV
  L011: [CONTEXT_SUBJECT_QUANTITY_SINGLE], // DE_SV
  L012: [CONTEXT_SUBJECT_QUANTITY_SINGLE], // WO_SV, NI_SV
  L013: [CONTEXT_SUBJECT_QUANTITY_SINGLE], // NI_SV, DE_SV
  L014: [CONTEXT_SUBJECT_QUANTITY_SINGLE], // DE_SV, WO_SV
  L015: [CONTEXT_SUBJECT_QUANTITY_SINGLE], // WO_SV, NI_SV, DE_SV
  L016: [CONTEXT_SUBJECT_QUANTITY_SINGLE], // KARA_SV
  L017: [CONTEXT_SUBJECT_QUANTITY_SINGLE], // MADE_SV
  L018: [CONTEXT_SUBJECT_QUANTITY_SINGLE], // NA - T_NO
  L019: [CONTEXT_SUBJECT_QUANTITY_SINGLE], // T - T_ADJ
  L020: [CONTEXT_SUBJECT_QUANTITY_SINGLE], // T - T_ADV
}

