// import {  
//   MODIFIERS_NA,
// } from '../constants/modifiersConstants';

// import {
//   __TYPENAME_PRE_MODIFIERS,
// } from '../constants/typeNameConstants';


// export const LESSON_PRE_MODIFIERS = {
//   L001: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T
//   L002: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // WA_TS, MO_TS
//   L003: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // GA_TS
//   L004: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // WA_TS, GA_TS
//   L005: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // WA_TS, MO_TS, GA_TS
//   L006: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // V
//   L007: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // V
//   L008: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // V
//   L009: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // WO_SV
//   L010: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // NI_SV
//   L011: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // DE_SV
//   L012: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // WO_SV, NI_SV
//   L013: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // NI_SV, DE_SV
//   L014: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // DE_SV, WO_SV
//   L015: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // WO_SV, NI_SV, DE_SV
//   L016: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // KARA_SV
//   L017: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // MADE_SV
//   L018: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // NA - T_NO
//   L019: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADJ
//   L020: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L021: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L022: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L023: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L024: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L025: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L026: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L027: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L028: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L029: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L030: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L031: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L032: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L033: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L034: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L035: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L036: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L037: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L038: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L039: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L040: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L041: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L042: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L043: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L044: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L045: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L046: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L047: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L048: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L049: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L050: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV
//   L051: { topicNoArray: [MODIFIERS_NA], subjectNoArray: [MODIFIERS_NA], topicAdjectiveArray: [MODIFIERS_NA], topicAdverbArray: [MODIFIERS_NA], subjectAdjectiveArray: [MODIFIERS_NA], subjectAdverbArray: [MODIFIERS_NA], __typename: __TYPENAME_PRE_MODIFIERS } as Util.PreModifiers, // T - T_ADV

// };


export default 'yay'