
import {
  NA,

  T,

  WA_TS,
  MO_TS,
  GA_TS,

  V,

  WO_SV,
  NI_SV,
  DE_SV,

  KARA_TS,
  MADE_TS,

  GENDER_MASCULINE,
  // GENDER_FEMININE,
  // GENDER_RANDOM,

  POLITENESS_CASUAL,
  // POLITENESS_FORMAL,
  // POLITENESS_HUMBLE,
  // POLITENESS_HONORIFIC,
  // POLITENESS_RANDOM,

  POLARITY_NEGATIVE,
  POLARITY_POSITIVE,

  // SENTENCE_ENDING_NE,
  // SENTENCE_ENDING_YO,
  // SENTENCE_ENDING_YO_NE,
  // SENTENCE_ENDING_RANDOM,

  // HAS_QUESTION,
  NOT_QUESTION,
  THEMES_DEFAULT,
  // RANDOM_QUESTION,
  // RANDOM_QUESTION,

} from '../constants/optionsConstants';

import {
  __TYPENAME_OPTIONS,
  __TYPENAME_MODIFIERS,
  __TYPENAME_SENTENCE_CONTEXT,
} from '../constants/typeNameConstants';


const LESSON_VARIATION = {
  L001: [ T ],
  L002: [ WA_TS, MO_TS ],
  L003: [ GA_TS ],
  L004: [ WA_TS, GA_TS ],
  L005: [ WA_TS, MO_TS, GA_TS ],
  L006: [ V ],
  L007: [ V ],
  L008: [ V ],
  L009: [ WO_SV ],
  L010: [ NI_SV ],
  L011: [ DE_SV ],
  L012: [ WO_SV, NI_SV ],
  L013: [ NI_SV, DE_SV ],
  L014: [ DE_SV, WO_SV ],
  L015: [ WA_TS, MO_TS, GA_TS ],
  L016: [ KARA_TS ],
  L017: [ MADE_TS ],
  L018: [ NA ],
  L019: [ T ],
  L020: [ T ],
  // L021:
  // L022: 
  // L023: 
  // L024: 
  // L025: 
  // L026: 
  // L027: 
};


const LESSON_POLITENESS = {
  L001: [ POLITENESS_CASUAL ],
  L002: [ POLITENESS_CASUAL ],
  L003: [ POLITENESS_CASUAL ],
  L004: [ POLITENESS_CASUAL ],
  L005: [ POLITENESS_CASUAL ],
  L006: [ POLITENESS_CASUAL ],
  L007: [ POLITENESS_CASUAL ],
  L008: [ POLITENESS_CASUAL ],
  L009: [ POLITENESS_CASUAL ],
  L010: [ POLITENESS_CASUAL ],
  L011: [ POLITENESS_CASUAL ],
  L012: [ POLITENESS_CASUAL ],
  L013: [ POLITENESS_CASUAL ],
  L014: [ POLITENESS_CASUAL ],
  L015: [ POLITENESS_CASUAL ],
  L016: [ POLITENESS_CASUAL ],
  L017: [ POLITENESS_CASUAL ],
  L018: [ POLITENESS_CASUAL ],
  L019: [ POLITENESS_CASUAL ],
  L020: [ POLITENESS_CASUAL ],
  // L021:
  // L022: 
  // L023: 
  // L024: 
  // L025: 
  // L026: 
  // L027: 
};


const LESSON_POLARITY = {
  L001: [ POLARITY_POSITIVE, POLARITY_NEGATIVE ],
  L002: [ POLARITY_POSITIVE, POLARITY_NEGATIVE ],
  L003: [ POLARITY_POSITIVE, POLARITY_NEGATIVE ],
  L004: [ POLARITY_POSITIVE, POLARITY_NEGATIVE ],
  L005: [ POLARITY_POSITIVE, POLARITY_NEGATIVE ],
  L006: [ POLARITY_POSITIVE, POLARITY_NEGATIVE ],
  L007: [ POLARITY_POSITIVE, POLARITY_NEGATIVE ],
  L008: [ POLARITY_POSITIVE, POLARITY_NEGATIVE ],
  L009: [ POLARITY_POSITIVE, POLARITY_NEGATIVE ],
  L010: [ POLARITY_POSITIVE, POLARITY_NEGATIVE ],
  L011: [ POLARITY_POSITIVE, POLARITY_NEGATIVE ],
  L012: [ POLARITY_POSITIVE, POLARITY_NEGATIVE ],
  L013: [ POLARITY_POSITIVE, POLARITY_NEGATIVE ],
  L014: [ POLARITY_POSITIVE, POLARITY_NEGATIVE ],
  L015: [ POLARITY_POSITIVE, POLARITY_NEGATIVE ],
  L016: [ POLARITY_POSITIVE, POLARITY_NEGATIVE ],
  L017: [ POLARITY_POSITIVE, POLARITY_NEGATIVE ],
  L018: [ POLARITY_POSITIVE, POLARITY_NEGATIVE ],
  L019: [ POLARITY_POSITIVE, POLARITY_NEGATIVE ],
  L020: [ POLARITY_POSITIVE, POLARITY_NEGATIVE ],
  // L021:
  // L022: 
  // L023: 
  // L024: 
  // L025: 
  // L026: 
  // L027: 
};


const LESSON_QUESTION = {
  L001: [ NOT_QUESTION ],
  L002: [ NOT_QUESTION ],
  L003: [ NOT_QUESTION ],
  L004: [ NOT_QUESTION ],
  L005: [ NOT_QUESTION ],
  L006: [ NOT_QUESTION ],
  L007: [ NOT_QUESTION ],
  L008: [ NOT_QUESTION ],
  L009: [ NOT_QUESTION ],
  L010: [ NOT_QUESTION ],
  L011: [ NOT_QUESTION ],
  L012: [ NOT_QUESTION ],
  L013: [ NOT_QUESTION ],
  L014: [ NOT_QUESTION ],
  L015: [ NOT_QUESTION ],
  L016: [ NOT_QUESTION ],
  L017: [ NOT_QUESTION ],
  L018: [ NOT_QUESTION ],
  L019: [ NOT_QUESTION ],
  L020: [ NOT_QUESTION ],
  // L021:
  // L022: 
  // L023: 
  // L024: 
  // L025: 
  // L026: 
  // L027: 
};


const LESSON_GENDER = {
  L001: [ GENDER_MASCULINE ],
  L002: [ GENDER_MASCULINE ],
  L003: [ GENDER_MASCULINE ],
  L004: [ GENDER_MASCULINE ],
  L005: [ GENDER_MASCULINE ],
  L006: [ GENDER_MASCULINE ],
  L007: [ GENDER_MASCULINE ],
  L008: [ GENDER_MASCULINE ],
  L009: [ GENDER_MASCULINE ],
  L010: [ GENDER_MASCULINE ],
  L011: [ GENDER_MASCULINE ],
  L012: [ GENDER_MASCULINE ],
  L013: [ GENDER_MASCULINE ],
  L014: [ GENDER_MASCULINE ],
  L015: [ GENDER_MASCULINE ],
  L016: [ GENDER_MASCULINE ],
  L017: [ GENDER_MASCULINE ],
  L018: [ GENDER_MASCULINE ],
  L019: [ GENDER_MASCULINE ],
  L020: [ GENDER_MASCULINE ],
  // L021:
  // L022: 
  // L023: 
  // L024: 
  // L025: 
  // L026: 
  // L027: 
};

const LESSON_THEMES = {
  L001: [ THEMES_DEFAULT ],
  L002: [ THEMES_DEFAULT ],
  L003: [ THEMES_DEFAULT ],
  L004: [ THEMES_DEFAULT ],
  L005: [ THEMES_DEFAULT ],
  L006: [ THEMES_DEFAULT ],
  L007: [ THEMES_DEFAULT ],
  L008: [ THEMES_DEFAULT ],
  L009: [ THEMES_DEFAULT ],
  L010: [ THEMES_DEFAULT ],
  L011: [ THEMES_DEFAULT ],
  L012: [ THEMES_DEFAULT ],
  L013: [ THEMES_DEFAULT ],
  L014: [ THEMES_DEFAULT ],
  L015: [ THEMES_DEFAULT ],
  L016: [ THEMES_DEFAULT ],
  L017: [ THEMES_DEFAULT ],
  L018: [ THEMES_DEFAULT ],
  L019: [ THEMES_DEFAULT ],
  L020: [ THEMES_DEFAULT ],
  // L021:
  // L022: 
  // L023: 
  // L024: 
  // L025: 
  // L026: 
  // L027: 
};


export const LESSON_PRE_OPTIONS = {
  L001: { variationArray: LESSON_VARIATION.L001, politenessArray: LESSON_POLITENESS.L001, polarityArray: LESSON_POLARITY.L001, questionArray: LESSON_QUESTION.L001, genderArray: LESSON_GENDER.L001, themesArray: LESSON_THEMES.L001, __typename: __TYPENAME_OPTIONS } as Util.PreOptions, // T
  L002: { variationArray: LESSON_VARIATION.L002, politenessArray: LESSON_POLITENESS.L002, polarityArray: LESSON_POLARITY.L002, questionArray: LESSON_QUESTION.L002, genderArray: LESSON_GENDER.L002, themesArray: LESSON_THEMES.L002, __typename: __TYPENAME_OPTIONS } as Util.PreOptions, // WA_TS, MO_TS
  L003: { variationArray: LESSON_VARIATION.L003, politenessArray: LESSON_POLITENESS.L003, polarityArray: LESSON_POLARITY.L003, questionArray: LESSON_QUESTION.L003, genderArray: LESSON_GENDER.L003, themesArray: LESSON_THEMES.L003, __typename: __TYPENAME_OPTIONS } as Util.PreOptions, // GA_TS
  L004: { variationArray: LESSON_VARIATION.L004, politenessArray: LESSON_POLITENESS.L004, polarityArray: LESSON_POLARITY.L004, questionArray: LESSON_QUESTION.L004, genderArray: LESSON_GENDER.L004, themesArray: LESSON_THEMES.L004, __typename: __TYPENAME_OPTIONS } as Util.PreOptions, // WA_TS, GA_TS
  L005: { variationArray: LESSON_VARIATION.L005, politenessArray: LESSON_POLITENESS.L005, polarityArray: LESSON_POLARITY.L005, questionArray: LESSON_QUESTION.L005, genderArray: LESSON_GENDER.L005, themesArray: LESSON_THEMES.L005, __typename: __TYPENAME_OPTIONS } as Util.PreOptions, // WA_TS, MO_TS, GA_TS
  L006: { variationArray: LESSON_VARIATION.L006, politenessArray: LESSON_POLITENESS.L006, polarityArray: LESSON_POLARITY.L006, questionArray: LESSON_QUESTION.L006, genderArray: LESSON_GENDER.L006, themesArray: LESSON_THEMES.L006, __typename: __TYPENAME_OPTIONS } as Util.PreOptions, // V
  L007: { variationArray: LESSON_VARIATION.L007, politenessArray: LESSON_POLITENESS.L007, polarityArray: LESSON_POLARITY.L007, questionArray: LESSON_QUESTION.L007, genderArray: LESSON_GENDER.L007, themesArray: LESSON_THEMES.L007, __typename: __TYPENAME_OPTIONS } as Util.PreOptions, // V
  L008: { variationArray: LESSON_VARIATION.L008, politenessArray: LESSON_POLITENESS.L008, polarityArray: LESSON_POLARITY.L008, questionArray: LESSON_QUESTION.L008, genderArray: LESSON_GENDER.L008, themesArray: LESSON_THEMES.L008, __typename: __TYPENAME_OPTIONS } as Util.PreOptions, // V
  L009: { variationArray: LESSON_VARIATION.L009, politenessArray: LESSON_POLITENESS.L009, polarityArray: LESSON_POLARITY.L009, questionArray: LESSON_QUESTION.L009, genderArray: LESSON_GENDER.L009, themesArray: LESSON_THEMES.L009, __typename: __TYPENAME_OPTIONS } as Util.PreOptions, // WO_SV
  L010: { variationArray: LESSON_VARIATION.L010, politenessArray: LESSON_POLITENESS.L010, polarityArray: LESSON_POLARITY.L010, questionArray: LESSON_QUESTION.L010, genderArray: LESSON_GENDER.L010, themesArray: LESSON_THEMES.L010, __typename: __TYPENAME_OPTIONS } as Util.PreOptions, // NI_SV
  L011: { variationArray: LESSON_VARIATION.L011, politenessArray: LESSON_POLITENESS.L011, polarityArray: LESSON_POLARITY.L011, questionArray: LESSON_QUESTION.L011, genderArray: LESSON_GENDER.L011, themesArray: LESSON_THEMES.L011, __typename: __TYPENAME_OPTIONS } as Util.PreOptions, // DE_SV
  L012: { variationArray: LESSON_VARIATION.L012, politenessArray: LESSON_POLITENESS.L012, polarityArray: LESSON_POLARITY.L012, questionArray: LESSON_QUESTION.L012, genderArray: LESSON_GENDER.L012, themesArray: LESSON_THEMES.L012, __typename: __TYPENAME_OPTIONS } as Util.PreOptions, // WO_SV, NI_SV
  L013: { variationArray: LESSON_VARIATION.L013, politenessArray: LESSON_POLITENESS.L013, polarityArray: LESSON_POLARITY.L013, questionArray: LESSON_QUESTION.L013, genderArray: LESSON_GENDER.L013, themesArray: LESSON_THEMES.L013, __typename: __TYPENAME_OPTIONS } as Util.PreOptions, // NI_SV, DE_SV
  L014: { variationArray: LESSON_VARIATION.L014, politenessArray: LESSON_POLITENESS.L014, polarityArray: LESSON_POLARITY.L014, questionArray: LESSON_QUESTION.L014, genderArray: LESSON_GENDER.L014, themesArray: LESSON_THEMES.L014, __typename: __TYPENAME_OPTIONS } as Util.PreOptions, // DE_SV, WO_SV
  L015: { variationArray: LESSON_VARIATION.L015, politenessArray: LESSON_POLITENESS.L015, polarityArray: LESSON_POLARITY.L015, questionArray: LESSON_QUESTION.L015, genderArray: LESSON_GENDER.L015, themesArray: LESSON_THEMES.L015, __typename: __TYPENAME_OPTIONS } as Util.PreOptions, // WO_SV, NI_SV, DE_SV
  L016: { variationArray: LESSON_VARIATION.L016, politenessArray: LESSON_POLITENESS.L016, polarityArray: LESSON_POLARITY.L016, questionArray: LESSON_QUESTION.L016, genderArray: LESSON_GENDER.L016, themesArray: LESSON_THEMES.L016, __typename: __TYPENAME_OPTIONS } as Util.PreOptions, // KARA_SV
  L017: { variationArray: LESSON_VARIATION.L017, politenessArray: LESSON_POLITENESS.L017, polarityArray: LESSON_POLARITY.L017, questionArray: LESSON_QUESTION.L017, genderArray: LESSON_GENDER.L017, themesArray: LESSON_THEMES.L017, __typename: __TYPENAME_OPTIONS } as Util.PreOptions, // MADE_SV
  L018: { variationArray: LESSON_VARIATION.L018, politenessArray: LESSON_POLITENESS.L018, polarityArray: LESSON_POLARITY.L018, questionArray: LESSON_QUESTION.L018, genderArray: LESSON_GENDER.L018, themesArray: LESSON_THEMES.L018, __typename: __TYPENAME_OPTIONS } as Util.PreOptions, // NA - T_NO
  L019: { variationArray: LESSON_VARIATION.L019, politenessArray: LESSON_POLITENESS.L019, polarityArray: LESSON_POLARITY.L019, questionArray: LESSON_QUESTION.L019, genderArray: LESSON_GENDER.L019, themesArray: LESSON_THEMES.L019, __typename: __TYPENAME_OPTIONS } as Util.PreOptions, // T - T_ADJ
  L020: { variationArray: LESSON_VARIATION.L020, politenessArray: LESSON_POLITENESS.L020, polarityArray: LESSON_POLARITY.L020, questionArray: LESSON_QUESTION.L020, genderArray: LESSON_GENDER.L020, themesArray: LESSON_THEMES.L020, __typename: __TYPENAME_OPTIONS } as Util.PreOptions, // T - T_ADV
  // L021:
  // L022: 
  // L023: 
  // L024: 
  // L025: 
  // L026: 
  // L027: 
};



