import {
  CONTEXT_INTENT_EXISTENCE,
  // CONTEXT_INTENT_POSSESSION,
  CONTEXT_INTENT_ACTION,

  // CONTEXT_PROXIMITY_RANDOM,
  // CONTEXT_PROXIMITY_ALONE,
  CONTEXT_PROXIMITY_NEAR,
  // CONTEXT_PROXIMITY_FAR,
  // CONTEXT_PROXIMITY_AT,
  // CONTEXT_PROXIMITY_INSIDE,

  // CONTEXT_TOPIC_DESTINATION_RANDOM,
  CONTEXT_TOPIC_DESTINATION_IRRELEVANT,
  CONTEXT_TOPIC_DESTINATION_NONE,
  // CONTEXT_Y_TOPIC_DESTINATION_ABOVE,
  // CONTEXT_Y_TOPIC_DESTINATION_BELOW,
  // CONTEXT_Y_TOPIC_DESTINATION_BEHIND,
  // CONTEXT_Y_TOPIC_DESTINATION_IN_FRONT,
  // CONTEXT_TOPIC_DESTINATION_ALONG,
  // CONTEXT_TOPIC_DESTINATION_BESIDE,
  // CONTEXT_TOPIC_DESTINATION_WITH,
  // CONTEXT_TOPIC_DESTINATION_BETWEEN,
  // CONTEXT_TOPIC_DESTINATION_THROUGH,
  // CONTEXT_TOPIC_DESTINATION_INSIDE,
  // CONTEXT_TOPIC_DESTINATION_OUTSIDE,

  // CONTEXT_DIRECTION_RANDOM,
  CONTEXT_DIRECTION_NONE,
  CONTEXT_DIRECTION_TOWARD,
  // CONTEXT_DIRECTION_AWAY,
  // CONTEXT_Y_DIRECTION_UP,
  // CONTEXT_Y_DIRECTION_DOWN,
  // CONTEXT_X_DIRECTION_LEFT,
  // CONTEXT_X_DIRECTION_RIGHT,
  // CONTEXT_X_DIRECTION_ACROSS,



  // CONTEXT_EVENT_OCCURANCE_RANDOM,
  // CONTEXT_EVENT_OCCURANCE_BEFORE_PAST,
  // CONTEXT_EVENT_OCCURANCE_PAST,
  // CONTEXT_EVENT_OCCURANCE_PAST_NOW,
  // CONTEXT_EVENT_OCCURANCE_PAST_FUTUREPAST,
  CONTEXT_EVENT_OCCURANCE_NOW,
  // CONTEXT_EVENT_OCCURANCE_NOW_FUTURE,
  // CONTEXT_EVENT_OCCURANCE_FUTURE,

  // CONTEXT_EVENT_DURATION_RANDOM,
  // CONTEXT_EVENT_DURATION_PARTIAL_CONTINUOUS,
  CONTEXT_EVENT_DURATION_COMPLETE, 

  // CONTEXT_POV_RANDOM,
  CONTEXT_POV_SELF_SINGULAR,
  // CONTEXT_POV_YOU_SINGULAR,
  // CONTEXT_POV_HESHEIT_SINGULAR,
  // CONTEXT_POV_WE_PLURAL,
  // CONTEXT_POV_YOU_PLURAL,
  // CONTEXT_POV_THEYTHOSE_PLURAL,



  // CONTEXT_SUBJECT_CONNECTION_RANDOM,
  // CONTEXT_SUBJECT_CONNECTION_IN_CONJUNCTION,
  CONTEXT_SUBJECT_CONNECTION_INDEPENDENT,

  // CONTEXT_SUBJECT_ROLE_RANDOM,
  CONTEXT_SUBJECT_ROLE_DIRECT,
  // CONTEXT_SUBJECT_ROLE_SECOND_HAND,
  // CONTEXT_SUBJECT_ROLE_ON_BEHALF_OF,
  // CONTEXT_SUBJECT_ROLE_BECAUSE_OF,


  // CONTEXT_SUBJECT_QUANTITY_RANDOM,
  CONTEXT_SUBJECT_QUANTITY_SINGLE,
  // CONTEXT_SUBJECT_QUANTITY_MULTIPLE,
} from '../constants/contextConstants';

import {
  __TYPENAME_SENTENCE_CONTEXT,
} from '../constants/typeNameConstants';


export const LESSON_TOPIC_INTENT = {
  L001: CONTEXT_INTENT_EXISTENCE,
  L002: CONTEXT_INTENT_EXISTENCE,
  L003: CONTEXT_INTENT_EXISTENCE,
  L004: CONTEXT_INTENT_EXISTENCE,
  L005: CONTEXT_INTENT_EXISTENCE,
  L006: CONTEXT_INTENT_ACTION,
  L007: CONTEXT_INTENT_ACTION,
  L008: CONTEXT_INTENT_ACTION,
  L009: CONTEXT_INTENT_ACTION,
  L010: CONTEXT_INTENT_ACTION,
  L011: CONTEXT_INTENT_ACTION,
  L012: CONTEXT_INTENT_ACTION,
  L013: CONTEXT_INTENT_ACTION,
  L014: CONTEXT_INTENT_ACTION,
  L015: CONTEXT_INTENT_ACTION,
  L016: '',
  L017: '',
  L018: '',
  L019: '',
  L020: '',
  // L021:
  // L022: 
  // L023: 
  // L024: 
  // L025: 
  // L026: 
  // L027: 
};


export const LESSON_PROXIMITY = {
  L001: CONTEXT_PROXIMITY_NEAR,
  L002: CONTEXT_PROXIMITY_NEAR,
  L003: CONTEXT_PROXIMITY_NEAR,
  L004: CONTEXT_PROXIMITY_NEAR,
  L005: CONTEXT_PROXIMITY_NEAR,
  L006: CONTEXT_PROXIMITY_NEAR,
  L007: CONTEXT_PROXIMITY_NEAR,
  L008: CONTEXT_PROXIMITY_NEAR,
  L009: CONTEXT_PROXIMITY_NEAR,
  L010: CONTEXT_PROXIMITY_NEAR,
  L011: CONTEXT_PROXIMITY_NEAR,
  L012: CONTEXT_PROXIMITY_NEAR,
  L013: CONTEXT_PROXIMITY_NEAR,
  L014: CONTEXT_PROXIMITY_NEAR,
  L015: CONTEXT_PROXIMITY_NEAR,
  L016: CONTEXT_PROXIMITY_NEAR,
  L017: CONTEXT_PROXIMITY_NEAR,
  L018: CONTEXT_PROXIMITY_NEAR,
  L019: CONTEXT_PROXIMITY_NEAR,
  L020: CONTEXT_PROXIMITY_NEAR,
  // L021:
  // L022: 
  // L023: 
  // L024: 
  // L025: 
  // L026: 
  // L027: 
};

export const LESSON_TOPIC_DESTINATION = {
  L001: CONTEXT_TOPIC_DESTINATION_NONE,
  L002: CONTEXT_TOPIC_DESTINATION_NONE,
  L003: CONTEXT_TOPIC_DESTINATION_NONE,
  L004: CONTEXT_TOPIC_DESTINATION_NONE,
  L005: CONTEXT_TOPIC_DESTINATION_NONE,
  L006: CONTEXT_TOPIC_DESTINATION_NONE,
  L007: CONTEXT_TOPIC_DESTINATION_NONE,
  L008: CONTEXT_TOPIC_DESTINATION_NONE,
  L009: CONTEXT_TOPIC_DESTINATION_IRRELEVANT,
  L010: CONTEXT_TOPIC_DESTINATION_IRRELEVANT,
  L011: CONTEXT_TOPIC_DESTINATION_IRRELEVANT,
  L012: CONTEXT_TOPIC_DESTINATION_IRRELEVANT,
  L013: CONTEXT_TOPIC_DESTINATION_IRRELEVANT,
  L014: CONTEXT_TOPIC_DESTINATION_IRRELEVANT,
  L015: CONTEXT_TOPIC_DESTINATION_IRRELEVANT,
  L016: CONTEXT_TOPIC_DESTINATION_NONE,
  L017: CONTEXT_TOPIC_DESTINATION_NONE,
  L018: CONTEXT_TOPIC_DESTINATION_NONE,
  L019: CONTEXT_TOPIC_DESTINATION_NONE,
  L020: CONTEXT_TOPIC_DESTINATION_NONE,
};

export const LESSON_DIRECTION = {
  L001: CONTEXT_DIRECTION_NONE,
  L002: CONTEXT_DIRECTION_NONE,
  L003: CONTEXT_DIRECTION_NONE,
  L004: CONTEXT_DIRECTION_NONE,
  L005: CONTEXT_DIRECTION_NONE,
  L006: CONTEXT_DIRECTION_NONE,
  L007: CONTEXT_DIRECTION_NONE,
  L008: CONTEXT_DIRECTION_NONE,
  L009: CONTEXT_DIRECTION_TOWARD,
  L010: CONTEXT_DIRECTION_TOWARD,
  L011: CONTEXT_DIRECTION_TOWARD,
  L012: CONTEXT_DIRECTION_TOWARD,
  L013: CONTEXT_DIRECTION_TOWARD,
  L014: CONTEXT_DIRECTION_TOWARD,
  L015: CONTEXT_DIRECTION_TOWARD,
  L016: CONTEXT_DIRECTION_NONE,
  L017: CONTEXT_DIRECTION_NONE,
  L018: CONTEXT_DIRECTION_NONE,
  L019: CONTEXT_DIRECTION_NONE,
  L020: CONTEXT_DIRECTION_NONE,
}

export const LESSON_EVENT_OCCURANCE = {
  L001: CONTEXT_EVENT_OCCURANCE_NOW,
  L002: CONTEXT_EVENT_OCCURANCE_NOW,
  L003: CONTEXT_EVENT_OCCURANCE_NOW,
  L004: CONTEXT_EVENT_OCCURANCE_NOW,
  L005: CONTEXT_EVENT_OCCURANCE_NOW,
  L006: CONTEXT_EVENT_OCCURANCE_NOW,
  L007: CONTEXT_EVENT_OCCURANCE_NOW,
  L008: CONTEXT_EVENT_OCCURANCE_NOW,
  L009: CONTEXT_EVENT_OCCURANCE_NOW,
  L010: CONTEXT_EVENT_OCCURANCE_NOW,
  L011: CONTEXT_EVENT_OCCURANCE_NOW,
  L012: CONTEXT_EVENT_OCCURANCE_NOW,
  L013: CONTEXT_EVENT_OCCURANCE_NOW,
  L014: CONTEXT_EVENT_OCCURANCE_NOW,
  L015: CONTEXT_EVENT_OCCURANCE_NOW,
  L016: CONTEXT_EVENT_OCCURANCE_NOW,
  L017: CONTEXT_EVENT_OCCURANCE_NOW,
  L018: CONTEXT_EVENT_OCCURANCE_NOW,
  L019: CONTEXT_EVENT_OCCURANCE_NOW,
  L020: CONTEXT_EVENT_OCCURANCE_NOW,
};

export const LESSON_EVENT_DURATION = {
  L001: CONTEXT_EVENT_DURATION_COMPLETE, 
  L002: CONTEXT_EVENT_DURATION_COMPLETE, 
  L003: CONTEXT_EVENT_DURATION_COMPLETE, 
  L004: CONTEXT_EVENT_DURATION_COMPLETE, 
  L005: CONTEXT_EVENT_DURATION_COMPLETE, 
  L006: CONTEXT_EVENT_DURATION_COMPLETE, 
  L007: CONTEXT_EVENT_DURATION_COMPLETE, 
  L008: CONTEXT_EVENT_DURATION_COMPLETE, 
  L009: CONTEXT_EVENT_DURATION_COMPLETE, 
  L010: CONTEXT_EVENT_DURATION_COMPLETE, 
  L011: CONTEXT_EVENT_DURATION_COMPLETE, 
  L012: CONTEXT_EVENT_DURATION_COMPLETE, 
  L013: CONTEXT_EVENT_DURATION_COMPLETE, 
  L014: CONTEXT_EVENT_DURATION_COMPLETE, 
  L015: CONTEXT_EVENT_DURATION_COMPLETE, 
  L016: CONTEXT_EVENT_DURATION_COMPLETE, 
  L017: CONTEXT_EVENT_DURATION_COMPLETE, 
  L018: CONTEXT_EVENT_DURATION_COMPLETE, 
  L019: CONTEXT_EVENT_DURATION_COMPLETE, 
  L020: CONTEXT_EVENT_DURATION_COMPLETE, 
}

export const LESSON_POV = {
  L001: CONTEXT_POV_SELF_SINGULAR, 
  L002: CONTEXT_POV_SELF_SINGULAR, 
  L003: CONTEXT_POV_SELF_SINGULAR, 
  L004: CONTEXT_POV_SELF_SINGULAR, 
  L005: CONTEXT_POV_SELF_SINGULAR, 
  L006: CONTEXT_POV_SELF_SINGULAR, 
  L007: CONTEXT_POV_SELF_SINGULAR, 
  L008: CONTEXT_POV_SELF_SINGULAR, 
  L009: CONTEXT_POV_SELF_SINGULAR, 
  L010: CONTEXT_POV_SELF_SINGULAR, 
  L011: CONTEXT_POV_SELF_SINGULAR, 
  L012: CONTEXT_POV_SELF_SINGULAR, 
  L013: CONTEXT_POV_SELF_SINGULAR, 
  L014: CONTEXT_POV_SELF_SINGULAR, 
  L015: CONTEXT_POV_SELF_SINGULAR, 
  L016: CONTEXT_POV_SELF_SINGULAR, 
  L017: CONTEXT_POV_SELF_SINGULAR, 
  L018: CONTEXT_POV_SELF_SINGULAR, 
  L019: CONTEXT_POV_SELF_SINGULAR, 
  L020: CONTEXT_POV_SELF_SINGULAR, 
};

export const LESSON_SUBJECT_CONNECTION = {
  L001: CONTEXT_SUBJECT_CONNECTION_INDEPENDENT,
  L002: CONTEXT_SUBJECT_CONNECTION_INDEPENDENT,
  L003: CONTEXT_SUBJECT_CONNECTION_INDEPENDENT,
  L004: CONTEXT_SUBJECT_CONNECTION_INDEPENDENT,
  L005: CONTEXT_SUBJECT_CONNECTION_INDEPENDENT,
  L006: CONTEXT_SUBJECT_CONNECTION_INDEPENDENT,
  L007: CONTEXT_SUBJECT_CONNECTION_INDEPENDENT,
  L008: CONTEXT_SUBJECT_CONNECTION_INDEPENDENT,
  L009: CONTEXT_SUBJECT_CONNECTION_INDEPENDENT,
  L010: CONTEXT_SUBJECT_CONNECTION_INDEPENDENT,
  L011: CONTEXT_SUBJECT_CONNECTION_INDEPENDENT,
  L012: CONTEXT_SUBJECT_CONNECTION_INDEPENDENT,
  L013: CONTEXT_SUBJECT_CONNECTION_INDEPENDENT,
  L014: CONTEXT_SUBJECT_CONNECTION_INDEPENDENT,
  L015: CONTEXT_SUBJECT_CONNECTION_INDEPENDENT,
  L016: CONTEXT_SUBJECT_CONNECTION_INDEPENDENT,
  L017: CONTEXT_SUBJECT_CONNECTION_INDEPENDENT,
  L018: CONTEXT_SUBJECT_CONNECTION_INDEPENDENT,
  L019: CONTEXT_SUBJECT_CONNECTION_INDEPENDENT,
  L020: CONTEXT_SUBJECT_CONNECTION_INDEPENDENT,
};

export const LESSON_SUBJECT_ROLE = {
  L001: CONTEXT_SUBJECT_ROLE_DIRECT,
  L002: CONTEXT_SUBJECT_ROLE_DIRECT,
  L003: CONTEXT_SUBJECT_ROLE_DIRECT,
  L004: CONTEXT_SUBJECT_ROLE_DIRECT,
  L005: CONTEXT_SUBJECT_ROLE_DIRECT,
  L006: CONTEXT_SUBJECT_ROLE_DIRECT,
  L007: CONTEXT_SUBJECT_ROLE_DIRECT,
  L008: CONTEXT_SUBJECT_ROLE_DIRECT,
  L009: CONTEXT_SUBJECT_ROLE_DIRECT,
  L010: CONTEXT_SUBJECT_ROLE_DIRECT,
  L011: CONTEXT_SUBJECT_ROLE_DIRECT,
  L012: CONTEXT_SUBJECT_ROLE_DIRECT,
  L013: CONTEXT_SUBJECT_ROLE_DIRECT,
  L014: CONTEXT_SUBJECT_ROLE_DIRECT,
  L015: CONTEXT_SUBJECT_ROLE_DIRECT,
  L016: CONTEXT_SUBJECT_ROLE_DIRECT,
  L017: CONTEXT_SUBJECT_ROLE_DIRECT,
  L018: CONTEXT_SUBJECT_ROLE_DIRECT,
  L019: CONTEXT_SUBJECT_ROLE_DIRECT,
  L020: CONTEXT_SUBJECT_ROLE_DIRECT,
}

export const LESSON_SUBJECT_QUANTITY = {
  L001: CONTEXT_SUBJECT_QUANTITY_SINGLE,
  L002: CONTEXT_SUBJECT_QUANTITY_SINGLE,
  L003: CONTEXT_SUBJECT_QUANTITY_SINGLE,
  L004: CONTEXT_SUBJECT_QUANTITY_SINGLE,
  L005: CONTEXT_SUBJECT_QUANTITY_SINGLE,
  L006: CONTEXT_SUBJECT_QUANTITY_SINGLE,
  L007: CONTEXT_SUBJECT_QUANTITY_SINGLE,
  L008: CONTEXT_SUBJECT_QUANTITY_SINGLE,
  L009: CONTEXT_SUBJECT_QUANTITY_SINGLE,
  L010: CONTEXT_SUBJECT_QUANTITY_SINGLE,
  L011: CONTEXT_SUBJECT_QUANTITY_SINGLE,
  L012: CONTEXT_SUBJECT_QUANTITY_SINGLE,
  L013: CONTEXT_SUBJECT_QUANTITY_SINGLE,
  L014: CONTEXT_SUBJECT_QUANTITY_SINGLE,
  L015: CONTEXT_SUBJECT_QUANTITY_SINGLE,
  L016: CONTEXT_SUBJECT_QUANTITY_SINGLE,
  L017: CONTEXT_SUBJECT_QUANTITY_SINGLE,
  L018: CONTEXT_SUBJECT_QUANTITY_SINGLE,
  L019: CONTEXT_SUBJECT_QUANTITY_SINGLE,
  L020: CONTEXT_SUBJECT_QUANTITY_SINGLE,
}

