FROM nginx:alpine

COPY --from=build-deps /usr/src/app/client/build/. /usr/share/nginx/html
COPY production.conf /usr/share/nginx/production.conf

# COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf

# RUN nginx -t 

EXPOSE 80
ENTRYPOINT ["nginx","-g","daemon off;"]
